//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/$Gson$Preconditions.java
//

#ifndef _$Gson$Preconditions_H_
#define _$Gson$Preconditions_H_

#include "J2ObjC_header.h"

@interface ComGoogleGsonInternal$Gson$Preconditions : NSObject

#pragma mark Public

+ (void)checkArgumentWithBoolean:(jboolean)condition;

+ (id)checkNotNullWithId:(id)obj;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternal$Gson$Preconditions)

FOUNDATION_EXPORT id ComGoogleGsonInternal$Gson$Preconditions_checkNotNullWithId_(id obj);

FOUNDATION_EXPORT void ComGoogleGsonInternal$Gson$Preconditions_checkArgumentWithBoolean_(jboolean condition);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternal$Gson$Preconditions)

#endif // _$Gson$Preconditions_H_
