//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/bind/CollectionTypeAdapterFactory.java
//

#include "$Gson$Types.h"
#include "CollectionTypeAdapterFactory.h"
#include "ConstructorConstructor.h"
#include "Gson.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "JsonReader.h"
#include "JsonToken.h"
#include "JsonWriter.h"
#include "ObjectConstructor.h"
#include "TypeAdapter.h"
#include "TypeAdapterRuntimeTypeWrapper.h"
#include "TypeToken.h"
#include "java/io/IOException.h"
#include "java/lang/reflect/Type.h"
#include "java/util/Collection.h"

@interface ComGoogleGsonInternalBindCollectionTypeAdapterFactory () {
 @public
  ComGoogleGsonInternalConstructorConstructor *constructorConstructor_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindCollectionTypeAdapterFactory, constructorConstructor_, ComGoogleGsonInternalConstructorConstructor *)

@interface ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter : ComGoogleGsonTypeAdapter {
 @public
  ComGoogleGsonTypeAdapter *elementTypeAdapter_;
  id<ComGoogleGsonInternalObjectConstructor> constructor_;
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                  withJavaLangReflectType:(id<JavaLangReflectType>)elementType
             withComGoogleGsonTypeAdapter:(ComGoogleGsonTypeAdapter *)elementTypeAdapter
withComGoogleGsonInternalObjectConstructor:(id<ComGoogleGsonInternalObjectConstructor>)constructor;

- (id<JavaUtilCollection>)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id<JavaUtilCollection>)collection;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter, elementTypeAdapter_, ComGoogleGsonTypeAdapter *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter, constructor_, id<ComGoogleGsonInternalObjectConstructor>)

__attribute__((unused)) static void ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter *self, ComGoogleGsonGson *context, id<JavaLangReflectType> elementType, ComGoogleGsonTypeAdapter *elementTypeAdapter, id<ComGoogleGsonInternalObjectConstructor> constructor);

__attribute__((unused)) static ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter *new_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(ComGoogleGsonGson *context, id<JavaLangReflectType> elementType, ComGoogleGsonTypeAdapter *elementTypeAdapter, id<ComGoogleGsonInternalObjectConstructor> constructor) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter)

@implementation ComGoogleGsonInternalBindCollectionTypeAdapterFactory

- (instancetype)initWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor {
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(self, constructorConstructor);
  return self;
}

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)typeToken {
  id<JavaLangReflectType> type = [((ComGoogleGsonReflectTypeToken *) nil_chk(typeToken)) getType];
  IOSClass *rawType = [typeToken getRawType];
  if (![JavaUtilCollection_class_() isAssignableFrom:rawType]) {
    return nil;
  }
  id<JavaLangReflectType> elementType = ComGoogleGsonInternal$Gson$Types_getCollectionElementTypeWithJavaLangReflectType_withIOSClass_(type, rawType);
  ComGoogleGsonTypeAdapter *elementTypeAdapter = [((ComGoogleGsonGson *) nil_chk(gson)) getAdapterWithComGoogleGsonReflectTypeToken:ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(elementType)];
  id<ComGoogleGsonInternalObjectConstructor> constructor = [((ComGoogleGsonInternalConstructorConstructor *) nil_chk(constructorConstructor_)) getWithComGoogleGsonReflectTypeToken:typeToken];
  ComGoogleGsonTypeAdapter *result = [new_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(gson, elementType, elementTypeAdapter, constructor) autorelease];
  return result;
}

- (void)dealloc {
  RELEASE_(constructorConstructor_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComGoogleGsonInternalConstructorConstructor:", "CollectionTypeAdapterFactory", NULL, 0x1, NULL, NULL },
    { "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "constructorConstructor_", NULL, 0x12, "Lcom.google.gson.internal.ConstructorConstructor;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lcom.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindCollectionTypeAdapterFactory = { 2, "CollectionTypeAdapterFactory", "com.google.gson.internal.bind", NULL, 0x11, 2, methods, 1, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComGoogleGsonInternalBindCollectionTypeAdapterFactory;
}

@end

void ComGoogleGsonInternalBindCollectionTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalBindCollectionTypeAdapterFactory *self, ComGoogleGsonInternalConstructorConstructor *constructorConstructor) {
  NSObject_init(self);
  JreStrongAssign(&self->constructorConstructor_, constructorConstructor);
}

ComGoogleGsonInternalBindCollectionTypeAdapterFactory *new_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor) {
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory *self = [ComGoogleGsonInternalBindCollectionTypeAdapterFactory alloc];
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(self, constructorConstructor);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindCollectionTypeAdapterFactory)

@implementation ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                  withJavaLangReflectType:(id<JavaLangReflectType>)elementType
             withComGoogleGsonTypeAdapter:(ComGoogleGsonTypeAdapter *)elementTypeAdapter
withComGoogleGsonInternalObjectConstructor:(id<ComGoogleGsonInternalObjectConstructor>)constructor {
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(self, context, elementType, elementTypeAdapter, constructor);
  return self;
}

- (id<JavaUtilCollection>)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if ([((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek] == JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, NULL)) {
    [inArg nextNull];
    return nil;
  }
  id<JavaUtilCollection> collection = [((id<ComGoogleGsonInternalObjectConstructor>) nil_chk(constructor_)) construct];
  [inArg beginArray];
  while ([inArg hasNext]) {
    id instance = [((ComGoogleGsonTypeAdapter *) nil_chk(elementTypeAdapter_)) readWithComGoogleGsonStreamJsonReader:inArg];
    [((id<JavaUtilCollection>) nil_chk(collection)) addWithId:instance];
  }
  [inArg endArray];
  return collection;
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id<JavaUtilCollection>)collection {
  if (collection == nil) {
    [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) beginArray];
  for (id __strong element in nil_chk(collection)) {
    [((ComGoogleGsonTypeAdapter *) nil_chk(elementTypeAdapter_)) writeWithComGoogleGsonStreamJsonWriter:outArg withId:element];
  }
  [outArg endArray];
}

- (void)dealloc {
  RELEASE_(elementTypeAdapter_);
  RELEASE_(constructor_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComGoogleGsonGson:withJavaLangReflectType:withComGoogleGsonTypeAdapter:withComGoogleGsonInternalObjectConstructor:", "Adapter", NULL, 0x1, NULL, NULL },
    { "readWithComGoogleGsonStreamJsonReader:", "read", "Ljava.util.Collection;", 0x1, "Ljava.io.IOException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "elementTypeAdapter_", NULL, 0x12, "Lcom.google.gson.TypeAdapter;", NULL, "Lcom/google/gson/TypeAdapter<TE;>;", .constantValue.asLong = 0 },
    { "constructor_", NULL, 0x12, "Lcom.google.gson.internal.ObjectConstructor;", NULL, "Lcom/google/gson/internal/ObjectConstructor<+Ljava/util/Collection<TE;>;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Collection;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter = { 2, "Adapter", "com.google.gson.internal.bind", "CollectionTypeAdapterFactory", 0x1a, 3, methods, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "<E:Ljava/lang/Object;>Lcom/google/gson/TypeAdapter<Ljava/util/Collection<TE;>;>;" };
  return &_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter;
}

@end

void ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter *self, ComGoogleGsonGson *context, id<JavaLangReflectType> elementType, ComGoogleGsonTypeAdapter *elementTypeAdapter, id<ComGoogleGsonInternalObjectConstructor> constructor) {
  ComGoogleGsonTypeAdapter_init(self);
  JreStrongAssignAndConsume(&self->elementTypeAdapter_, new_ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_initWithComGoogleGsonGson_withComGoogleGsonTypeAdapter_withJavaLangReflectType_(context, elementTypeAdapter, elementType));
  JreStrongAssign(&self->constructor_, constructor);
}

ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter *new_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(ComGoogleGsonGson *context, id<JavaLangReflectType> elementType, ComGoogleGsonTypeAdapter *elementTypeAdapter, id<ComGoogleGsonInternalObjectConstructor> constructor) {
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter *self = [ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter alloc];
  ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter_initWithComGoogleGsonGson_withJavaLangReflectType_withComGoogleGsonTypeAdapter_withComGoogleGsonInternalObjectConstructor_(self, context, elementType, elementTypeAdapter, constructor);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindCollectionTypeAdapterFactory_Adapter)
