//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/ConstructorConstructor.java
//

#ifndef _ConstructorConstructor_H_
#define _ConstructorConstructor_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonReflectTypeToken;
@protocol ComGoogleGsonInternalObjectConstructor;
@protocol JavaUtilMap;

@interface ComGoogleGsonInternalConstructorConstructor : NSObject

#pragma mark Public

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)instanceCreators;

- (id<ComGoogleGsonInternalObjectConstructor>)getWithComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)typeToken;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalConstructorConstructor)

FOUNDATION_EXPORT void ComGoogleGsonInternalConstructorConstructor_initWithJavaUtilMap_(ComGoogleGsonInternalConstructorConstructor *self, id<JavaUtilMap> instanceCreators);

FOUNDATION_EXPORT ComGoogleGsonInternalConstructorConstructor *new_ComGoogleGsonInternalConstructorConstructor_initWithJavaUtilMap_(id<JavaUtilMap> instanceCreators) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalConstructorConstructor)

#endif // _ConstructorConstructor_H_
