//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/DefaultDateTypeAdapter.java
//

#ifndef _DefaultDateTypeAdapter_H_
#define _DefaultDateTypeAdapter_H_

#include "J2ObjC_header.h"
#include "JsonDeserializer.h"
#include "JsonSerializer.h"

@class ComGoogleGsonJsonElement;
@class JavaTextDateFormat;
@class JavaUtilDate;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol ComGoogleGsonJsonSerializationContext;
@protocol JavaLangReflectType;

@interface ComGoogleGsonDefaultDateTypeAdapter : NSObject < ComGoogleGsonJsonSerializer, ComGoogleGsonJsonDeserializer >

#pragma mark Public

- (instancetype)initWithInt:(jint)dateStyle
                    withInt:(jint)timeStyle;

- (JavaUtilDate *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                  withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
              withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

- (ComGoogleGsonJsonElement *)serializeWithId:(JavaUtilDate *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)init;

- (instancetype)initWithJavaTextDateFormat:(JavaTextDateFormat *)enUsFormat
                    withJavaTextDateFormat:(JavaTextDateFormat *)localFormat;

- (instancetype)initWithInt:(jint)style;

- (instancetype)initWithNSString:(NSString *)datePattern;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonDefaultDateTypeAdapter)

FOUNDATION_EXPORT void ComGoogleGsonDefaultDateTypeAdapter_init(ComGoogleGsonDefaultDateTypeAdapter *self);

FOUNDATION_EXPORT ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(ComGoogleGsonDefaultDateTypeAdapter *self, NSString *datePattern);

FOUNDATION_EXPORT ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(NSString *datePattern) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(ComGoogleGsonDefaultDateTypeAdapter *self, jint style);

FOUNDATION_EXPORT ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(jint style) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(ComGoogleGsonDefaultDateTypeAdapter *self, jint dateStyle, jint timeStyle);

FOUNDATION_EXPORT ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(jint dateStyle, jint timeStyle) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(ComGoogleGsonDefaultDateTypeAdapter *self, JavaTextDateFormat *enUsFormat, JavaTextDateFormat *localFormat);

FOUNDATION_EXPORT ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(JavaTextDateFormat *enUsFormat, JavaTextDateFormat *localFormat) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonDefaultDateTypeAdapter)

#endif // _DefaultDateTypeAdapter_H_
