//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/DefaultDateTypeAdapter.java
//

#include "DefaultDateTypeAdapter.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonParseException.h"
#include "JsonPrimitive.h"
#include "JsonSerializationContext.h"
#include "JsonSyntaxException.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/reflect/Type.h"
#include "java/sql/Date.h"
#include "java/sql/Timestamp.h"
#include "java/text/DateFormat.h"
#include "java/text/ParseException.h"
#include "java/text/SimpleDateFormat.h"
#include "java/util/Date.h"
#include "java/util/Locale.h"
#include "java/util/TimeZone.h"

@interface ComGoogleGsonDefaultDateTypeAdapter () {
 @public
  JavaTextDateFormat *enUsFormat_;
  JavaTextDateFormat *localFormat_;
  JavaTextDateFormat *iso8601Format_;
}

- (JavaUtilDate *)deserializeToDateWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonDefaultDateTypeAdapter, enUsFormat_, JavaTextDateFormat *)
J2OBJC_FIELD_SETTER(ComGoogleGsonDefaultDateTypeAdapter, localFormat_, JavaTextDateFormat *)
J2OBJC_FIELD_SETTER(ComGoogleGsonDefaultDateTypeAdapter, iso8601Format_, JavaTextDateFormat *)

__attribute__((unused)) static JavaUtilDate *ComGoogleGsonDefaultDateTypeAdapter_deserializeToDateWithComGoogleGsonJsonElement_(ComGoogleGsonDefaultDateTypeAdapter *self, ComGoogleGsonJsonElement *json);

@implementation ComGoogleGsonDefaultDateTypeAdapter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonDefaultDateTypeAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithNSString:(NSString *)datePattern {
  ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(self, datePattern);
  return self;
}

- (instancetype)initWithInt:(jint)style {
  ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(self, style);
  return self;
}

- (instancetype)initWithInt:(jint)dateStyle
                    withInt:(jint)timeStyle {
  ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(self, dateStyle, timeStyle);
  return self;
}

- (instancetype)initWithJavaTextDateFormat:(JavaTextDateFormat *)enUsFormat
                    withJavaTextDateFormat:(JavaTextDateFormat *)localFormat {
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, enUsFormat, localFormat);
  return self;
}

- (ComGoogleGsonJsonElement *)serializeWithId:(JavaUtilDate *)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
    withComGoogleGsonJsonSerializationContext:(id<ComGoogleGsonJsonSerializationContext>)context {
  @synchronized(localFormat_) {
    NSString *dateFormatAsString = [((JavaTextDateFormat *) nil_chk(enUsFormat_)) formatWithJavaUtilDate:src];
    return [new_ComGoogleGsonJsonPrimitive_initWithNSString_(dateFormatAsString) autorelease];
  }
}

- (JavaUtilDate *)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                                  withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
              withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context {
  if (!([json isKindOfClass:[ComGoogleGsonJsonPrimitive class]])) {
    @throw [new_ComGoogleGsonJsonParseException_initWithNSString_(@"The date should be a string value") autorelease];
  }
  JavaUtilDate *date = ComGoogleGsonDefaultDateTypeAdapter_deserializeToDateWithComGoogleGsonJsonElement_(self, json);
  if (typeOfT == JavaUtilDate_class_()) {
    return date;
  }
  else if (typeOfT == JavaSqlTimestamp_class_()) {
    return [new_JavaSqlTimestamp_initWithLong_([((JavaUtilDate *) nil_chk(date)) getTime]) autorelease];
  }
  else if (typeOfT == JavaSqlDate_class_()) {
    return [new_JavaSqlDate_initWithLong_([((JavaUtilDate *) nil_chk(date)) getTime]) autorelease];
  }
  else {
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("@$@", [self getClass], @" cannot deserialize to ", typeOfT)) autorelease];
  }
}

- (JavaUtilDate *)deserializeToDateWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json {
  return ComGoogleGsonDefaultDateTypeAdapter_deserializeToDateWithComGoogleGsonJsonElement_(self, json);
}

- (NSString *)description {
  JavaLangStringBuilder *sb = [new_JavaLangStringBuilder_init() autorelease];
  [sb appendWithNSString:[ComGoogleGsonDefaultDateTypeAdapter_class_() getSimpleName]];
  [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([sb appendWithChar:'('])) appendWithNSString:[[((JavaTextDateFormat *) nil_chk(localFormat_)) getClass] getSimpleName]])) appendWithChar:')'];
  return [sb description];
}

- (void)dealloc {
  RELEASE_(enUsFormat_);
  RELEASE_(localFormat_);
  RELEASE_(iso8601Format_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "DefaultDateTypeAdapter", NULL, 0x0, NULL, NULL },
    { "initWithNSString:", "DefaultDateTypeAdapter", NULL, 0x0, NULL, NULL },
    { "initWithInt:", "DefaultDateTypeAdapter", NULL, 0x0, NULL, NULL },
    { "initWithInt:withInt:", "DefaultDateTypeAdapter", NULL, 0x1, NULL, NULL },
    { "initWithJavaTextDateFormat:withJavaTextDateFormat:", "DefaultDateTypeAdapter", NULL, 0x0, NULL, NULL },
    { "serializeWithId:withJavaLangReflectType:withComGoogleGsonJsonSerializationContext:", "serialize", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:", "deserialize", "Ljava.util.Date;", 0x1, "Lcom.google.gson.JsonParseException;", NULL },
    { "deserializeToDateWithComGoogleGsonJsonElement:", "deserializeToDate", "Ljava.util.Date;", 0x2, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "enUsFormat_", NULL, 0x12, "Ljava.text.DateFormat;", NULL, NULL, .constantValue.asLong = 0 },
    { "localFormat_", NULL, 0x12, "Ljava.text.DateFormat;", NULL, NULL, .constantValue.asLong = 0 },
    { "iso8601Format_", NULL, 0x12, "Ljava.text.DateFormat;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonDefaultDateTypeAdapter = { 2, "DefaultDateTypeAdapter", "com.google.gson", NULL, 0x10, 9, methods, 3, fields, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Lcom/google/gson/JsonSerializer<Ljava/util/Date;>;Lcom/google/gson/JsonDeserializer<Ljava/util/Date;>;" };
  return &_ComGoogleGsonDefaultDateTypeAdapter;
}

@end

void ComGoogleGsonDefaultDateTypeAdapter_init(ComGoogleGsonDefaultDateTypeAdapter *self) {
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, JavaTextDateFormat_getDateTimeInstanceWithInt_withInt_withJavaUtilLocale_(JavaTextDateFormat_DEFAULT, JavaTextDateFormat_DEFAULT, JreLoadStatic(JavaUtilLocale, US_)), JavaTextDateFormat_getDateTimeInstanceWithInt_withInt_(JavaTextDateFormat_DEFAULT, JavaTextDateFormat_DEFAULT));
}

ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_init() {
  ComGoogleGsonDefaultDateTypeAdapter *self = [ComGoogleGsonDefaultDateTypeAdapter alloc];
  ComGoogleGsonDefaultDateTypeAdapter_init(self);
  return self;
}

void ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(ComGoogleGsonDefaultDateTypeAdapter *self, NSString *datePattern) {
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, [new_JavaTextSimpleDateFormat_initWithNSString_withJavaUtilLocale_(datePattern, JreLoadStatic(JavaUtilLocale, US_)) autorelease], [new_JavaTextSimpleDateFormat_initWithNSString_(datePattern) autorelease]);
}

ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(NSString *datePattern) {
  ComGoogleGsonDefaultDateTypeAdapter *self = [ComGoogleGsonDefaultDateTypeAdapter alloc];
  ComGoogleGsonDefaultDateTypeAdapter_initWithNSString_(self, datePattern);
  return self;
}

void ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(ComGoogleGsonDefaultDateTypeAdapter *self, jint style) {
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, JavaTextDateFormat_getDateInstanceWithInt_withJavaUtilLocale_(style, JreLoadStatic(JavaUtilLocale, US_)), JavaTextDateFormat_getDateInstanceWithInt_(style));
}

ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(jint style) {
  ComGoogleGsonDefaultDateTypeAdapter *self = [ComGoogleGsonDefaultDateTypeAdapter alloc];
  ComGoogleGsonDefaultDateTypeAdapter_initWithInt_(self, style);
  return self;
}

void ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(ComGoogleGsonDefaultDateTypeAdapter *self, jint dateStyle, jint timeStyle) {
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, JavaTextDateFormat_getDateTimeInstanceWithInt_withInt_withJavaUtilLocale_(dateStyle, timeStyle, JreLoadStatic(JavaUtilLocale, US_)), JavaTextDateFormat_getDateTimeInstanceWithInt_withInt_(dateStyle, timeStyle));
}

ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(jint dateStyle, jint timeStyle) {
  ComGoogleGsonDefaultDateTypeAdapter *self = [ComGoogleGsonDefaultDateTypeAdapter alloc];
  ComGoogleGsonDefaultDateTypeAdapter_initWithInt_withInt_(self, dateStyle, timeStyle);
  return self;
}

void ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(ComGoogleGsonDefaultDateTypeAdapter *self, JavaTextDateFormat *enUsFormat, JavaTextDateFormat *localFormat) {
  NSObject_init(self);
  JreStrongAssign(&self->enUsFormat_, enUsFormat);
  JreStrongAssign(&self->localFormat_, localFormat);
  JreStrongAssignAndConsume(&self->iso8601Format_, new_JavaTextSimpleDateFormat_initWithNSString_withJavaUtilLocale_(@"yyyy-MM-dd'T'HH:mm:ss'Z'", JreLoadStatic(JavaUtilLocale, US_)));
  [self->iso8601Format_ setTimeZoneWithJavaUtilTimeZone:JavaUtilTimeZone_getTimeZoneWithNSString_(@"UTC")];
}

ComGoogleGsonDefaultDateTypeAdapter *new_ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(JavaTextDateFormat *enUsFormat, JavaTextDateFormat *localFormat) {
  ComGoogleGsonDefaultDateTypeAdapter *self = [ComGoogleGsonDefaultDateTypeAdapter alloc];
  ComGoogleGsonDefaultDateTypeAdapter_initWithJavaTextDateFormat_withJavaTextDateFormat_(self, enUsFormat, localFormat);
  return self;
}

JavaUtilDate *ComGoogleGsonDefaultDateTypeAdapter_deserializeToDateWithComGoogleGsonJsonElement_(ComGoogleGsonDefaultDateTypeAdapter *self, ComGoogleGsonJsonElement *json) {
  @synchronized(self->localFormat_) {
    @try {
      return [((JavaTextDateFormat *) nil_chk(self->localFormat_)) parseWithNSString:[((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString]];
    }
    @catch (JavaTextParseException *ignored) {
    }
    @try {
      return [((JavaTextDateFormat *) nil_chk(self->enUsFormat_)) parseWithNSString:[((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString]];
    }
    @catch (JavaTextParseException *ignored) {
    }
    @try {
      return [((JavaTextDateFormat *) nil_chk(self->iso8601Format_)) parseWithNSString:[((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString]];
    }
    @catch (JavaTextParseException *e) {
      @throw [new_ComGoogleGsonJsonSyntaxException_initWithNSString_withJavaLangThrowable_([((ComGoogleGsonJsonElement *) nil_chk(json)) getAsString], e) autorelease];
    }
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonDefaultDateTypeAdapter)
