//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/ExclusionStrategy.java
//

#ifndef _ExclusionStrategy_H_
#define _ExclusionStrategy_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonFieldAttributes;
@class IOSClass;

@protocol ComGoogleGsonExclusionStrategy < NSObject, JavaObject >

- (jboolean)shouldSkipFieldWithComGoogleGsonFieldAttributes:(ComGoogleGsonFieldAttributes *)f;

- (jboolean)shouldSkipClassWithIOSClass:(IOSClass *)clazz;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonExclusionStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonExclusionStrategy)

#endif // _ExclusionStrategy_H_
