//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/FieldAttributes.java
//

#ifndef _FieldAttributes_H_
#define _FieldAttributes_H_

#include "J2ObjC_header.h"

@class IOSClass;
@class JavaLangReflectField;
@protocol JavaLangAnnotationAnnotation;
@protocol JavaLangReflectType;
@protocol JavaUtilCollection;

@interface ComGoogleGsonFieldAttributes : NSObject

#pragma mark Public

- (instancetype)initWithJavaLangReflectField:(JavaLangReflectField *)f;

- (id)getAnnotationWithIOSClass:(IOSClass *)annotation;

- (id<JavaUtilCollection>)getAnnotations;

- (IOSClass *)getDeclaredClass;

- (id<JavaLangReflectType>)getDeclaredType;

- (IOSClass *)getDeclaringClass;

- (NSString *)getName;

- (jboolean)hasModifierWithInt:(jint)modifier;

#pragma mark Package-Private

- (id)getWithId:(id)instance;

- (jboolean)isSynthetic;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldAttributes)

FOUNDATION_EXPORT void ComGoogleGsonFieldAttributes_initWithJavaLangReflectField_(ComGoogleGsonFieldAttributes *self, JavaLangReflectField *f);

FOUNDATION_EXPORT ComGoogleGsonFieldAttributes *new_ComGoogleGsonFieldAttributes_initWithJavaLangReflectField_(JavaLangReflectField *f) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldAttributes)

#endif // _FieldAttributes_H_
