//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/FieldNamingStrategy.java
//

#ifndef _FieldNamingStrategy_H_
#define _FieldNamingStrategy_H_

#include "J2ObjC_header.h"

@class JavaLangReflectField;

@protocol ComGoogleGsonFieldNamingStrategy < NSObject, JavaObject >

- (NSString *)translateNameWithJavaLangReflectField:(JavaLangReflectField *)f;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonFieldNamingStrategy)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonFieldNamingStrategy)

#endif // _FieldNamingStrategy_H_
