//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/Gson.java
//

#include "ArrayTypeAdapter.h"
#include "CollectionTypeAdapterFactory.h"
#include "ConstructorConstructor.h"
#include "DateTypeAdapter.h"
#include "Excluder.h"
#include "FieldNamingPolicy.h"
#include "FieldNamingStrategy.h"
#include "Gson.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "JsonAdapterAnnotationTypeAdapterFactory.h"
#include "JsonDeserializationContext.h"
#include "JsonElement.h"
#include "JsonIOException.h"
#include "JsonNull.h"
#include "JsonParseException.h"
#include "JsonReader.h"
#include "JsonSerializationContext.h"
#include "JsonSyntaxException.h"
#include "JsonToken.h"
#include "JsonTreeReader.h"
#include "JsonTreeWriter.h"
#include "JsonWriter.h"
#include "LongSerializationPolicy.h"
#include "MalformedJsonException.h"
#include "MapTypeAdapterFactory.h"
#include "ObjectTypeAdapter.h"
#include "Primitives.h"
#include "ReflectiveTypeAdapterFactory.h"
#include "SqlDateTypeAdapter.h"
#include "Streams.h"
#include "TimeTypeAdapter.h"
#include "TypeAdapter.h"
#include "TypeAdapterFactory.h"
#include "TypeAdapters.h"
#include "TypeToken.h"
#include "java/io/EOFException.h"
#include "java/io/IOException.h"
#include "java/io/Reader.h"
#include "java/io/StringReader.h"
#include "java/io/StringWriter.h"
#include "java/io/Writer.h"
#include "java/lang/Appendable.h"
#include "java/lang/AssertionError.h"
#include "java/lang/Double.h"
#include "java/lang/Float.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Long.h"
#include "java/lang/RuntimeException.h"
#include "java/lang/StringBuilder.h"
#include "java/lang/ThreadLocal.h"
#include "java/lang/reflect/Type.h"
#include "java/math/BigDecimal.h"
#include "java/math/BigInteger.h"
#include "java/util/ArrayList.h"
#include "java/util/Collections.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Map.h"

@interface ComGoogleGsonGson () {
 @public
  JavaLangThreadLocal *calls_;
  id<JavaUtilMap> typeTokenCache_;
  id<JavaUtilList> factories_;
  ComGoogleGsonInternalConstructorConstructor *constructorConstructor_;
  jboolean serializeNulls_;
  jboolean htmlSafe_;
  jboolean generateNonExecutableJson_;
  jboolean prettyPrinting_;
}

- (ComGoogleGsonTypeAdapter *)doubleAdapterWithBoolean:(jboolean)serializeSpecialFloatingPointValues;

- (ComGoogleGsonTypeAdapter *)floatAdapterWithBoolean:(jboolean)serializeSpecialFloatingPointValues;

- (void)checkValidFloatingPointWithDouble:(jdouble)value;

- (ComGoogleGsonTypeAdapter *)longAdapterWithComGoogleGsonLongSerializationPolicyEnum:(ComGoogleGsonLongSerializationPolicyEnum *)longSerializationPolicy;

+ (void)assertFullConsumptionWithId:(id)obj
  withComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonGson, calls_, JavaLangThreadLocal *)
J2OBJC_FIELD_SETTER(ComGoogleGsonGson, typeTokenCache_, id<JavaUtilMap>)
J2OBJC_FIELD_SETTER(ComGoogleGsonGson, factories_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComGoogleGsonGson, constructorConstructor_, ComGoogleGsonInternalConstructorConstructor *)

static NSString *ComGoogleGsonGson_JSON_NON_EXECUTABLE_PREFIX_ = @")]}'\n";
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonGson, JSON_NON_EXECUTABLE_PREFIX_, NSString *)

__attribute__((unused)) static ComGoogleGsonTypeAdapter *ComGoogleGsonGson_doubleAdapterWithBoolean_(ComGoogleGsonGson *self, jboolean serializeSpecialFloatingPointValues);

__attribute__((unused)) static ComGoogleGsonTypeAdapter *ComGoogleGsonGson_floatAdapterWithBoolean_(ComGoogleGsonGson *self, jboolean serializeSpecialFloatingPointValues);

__attribute__((unused)) static void ComGoogleGsonGson_checkValidFloatingPointWithDouble_(ComGoogleGsonGson *self, jdouble value);

__attribute__((unused)) static ComGoogleGsonTypeAdapter *ComGoogleGsonGson_longAdapterWithComGoogleGsonLongSerializationPolicyEnum_(ComGoogleGsonGson *self, ComGoogleGsonLongSerializationPolicyEnum *longSerializationPolicy);

__attribute__((unused)) static void ComGoogleGsonGson_assertFullConsumptionWithId_withComGoogleGsonStreamJsonReader_(id obj, ComGoogleGsonStreamJsonReader *reader);

@interface ComGoogleGsonGson_FutureTypeAdapter () {
 @public
  ComGoogleGsonTypeAdapter *delegate_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonGson_FutureTypeAdapter, delegate_, ComGoogleGsonTypeAdapter *)

@interface ComGoogleGsonGson_$1 : NSObject < ComGoogleGsonJsonDeserializationContext > {
 @public
  ComGoogleGsonGson *this$0_;
}

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT;

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGson_$1)

J2OBJC_FIELD_SETTER(ComGoogleGsonGson_$1, this$0_, ComGoogleGsonGson *)

__attribute__((unused)) static void ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(ComGoogleGsonGson_$1 *self, ComGoogleGsonGson *outer$);

__attribute__((unused)) static ComGoogleGsonGson_$1 *new_ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGson_$1)

@interface ComGoogleGsonGson_$2 : NSObject < ComGoogleGsonJsonSerializationContext > {
 @public
  ComGoogleGsonGson *this$0_;
}

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src;

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc;

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGson_$2)

J2OBJC_FIELD_SETTER(ComGoogleGsonGson_$2, this$0_, ComGoogleGsonGson *)

__attribute__((unused)) static void ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(ComGoogleGsonGson_$2 *self, ComGoogleGsonGson *outer$);

__attribute__((unused)) static ComGoogleGsonGson_$2 *new_ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGson_$2)

@interface ComGoogleGsonGson_$3 : ComGoogleGsonTypeAdapter {
 @public
  ComGoogleGsonGson *this$0_;
}

- (JavaLangDouble *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value;

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGson_$3)

J2OBJC_FIELD_SETTER(ComGoogleGsonGson_$3, this$0_, ComGoogleGsonGson *)

__attribute__((unused)) static void ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(ComGoogleGsonGson_$3 *self, ComGoogleGsonGson *outer$);

__attribute__((unused)) static ComGoogleGsonGson_$3 *new_ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGson_$3)

@interface ComGoogleGsonGson_$4 : ComGoogleGsonTypeAdapter {
 @public
  ComGoogleGsonGson *this$0_;
}

- (JavaLangFloat *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value;

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGson_$4)

J2OBJC_FIELD_SETTER(ComGoogleGsonGson_$4, this$0_, ComGoogleGsonGson *)

__attribute__((unused)) static void ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(ComGoogleGsonGson_$4 *self, ComGoogleGsonGson *outer$);

__attribute__((unused)) static ComGoogleGsonGson_$4 *new_ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGson_$4)

@interface ComGoogleGsonGson_$5 : ComGoogleGsonTypeAdapter

- (NSNumber *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg;

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonGson_$5)

__attribute__((unused)) static void ComGoogleGsonGson_$5_init(ComGoogleGsonGson_$5 *self);

__attribute__((unused)) static ComGoogleGsonGson_$5 *new_ComGoogleGsonGson_$5_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonGson_$5)

@implementation ComGoogleGsonGson

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonGson_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonInternalExcluder:(ComGoogleGsonInternalExcluder *)excluder
                 withComGoogleGsonFieldNamingStrategy:(id<ComGoogleGsonFieldNamingStrategy>)fieldNamingPolicy
                                      withJavaUtilMap:(id<JavaUtilMap>)instanceCreators
                                          withBoolean:(jboolean)serializeNulls
                                          withBoolean:(jboolean)complexMapKeySerialization
                                          withBoolean:(jboolean)generateNonExecutableGson
                                          withBoolean:(jboolean)htmlSafe
                                          withBoolean:(jboolean)prettyPrinting
                                          withBoolean:(jboolean)serializeSpecialFloatingPointValues
         withComGoogleGsonLongSerializationPolicyEnum:(ComGoogleGsonLongSerializationPolicyEnum *)longSerializationPolicy
                                     withJavaUtilList:(id<JavaUtilList>)typeAdapterFactories {
  ComGoogleGsonGson_initWithComGoogleGsonInternalExcluder_withComGoogleGsonFieldNamingStrategy_withJavaUtilMap_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withComGoogleGsonLongSerializationPolicyEnum_withJavaUtilList_(self, excluder, fieldNamingPolicy, instanceCreators, serializeNulls, complexMapKeySerialization, generateNonExecutableGson, htmlSafe, prettyPrinting, serializeSpecialFloatingPointValues, longSerializationPolicy, typeAdapterFactories);
  return self;
}

- (ComGoogleGsonTypeAdapter *)doubleAdapterWithBoolean:(jboolean)serializeSpecialFloatingPointValues {
  return ComGoogleGsonGson_doubleAdapterWithBoolean_(self, serializeSpecialFloatingPointValues);
}

- (ComGoogleGsonTypeAdapter *)floatAdapterWithBoolean:(jboolean)serializeSpecialFloatingPointValues {
  return ComGoogleGsonGson_floatAdapterWithBoolean_(self, serializeSpecialFloatingPointValues);
}

- (void)checkValidFloatingPointWithDouble:(jdouble)value {
  ComGoogleGsonGson_checkValidFloatingPointWithDouble_(self, value);
}

- (ComGoogleGsonTypeAdapter *)longAdapterWithComGoogleGsonLongSerializationPolicyEnum:(ComGoogleGsonLongSerializationPolicyEnum *)longSerializationPolicy {
  return ComGoogleGsonGson_longAdapterWithComGoogleGsonLongSerializationPolicyEnum_(self, longSerializationPolicy);
}

- (ComGoogleGsonTypeAdapter *)getAdapterWithComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type {
  ComGoogleGsonTypeAdapter *cached = [((id<JavaUtilMap>) nil_chk(typeTokenCache_)) getWithId:type];
  if (cached != nil) {
    return (ComGoogleGsonTypeAdapter *) check_class_cast(cached, [ComGoogleGsonTypeAdapter class]);
  }
  id<JavaUtilMap> threadCalls = [((JavaLangThreadLocal *) nil_chk(calls_)) get];
  jboolean requiresThreadLocalCleanup = false;
  if (threadCalls == nil) {
    threadCalls = [new_JavaUtilHashMap_init() autorelease];
    [calls_ setWithId:threadCalls];
    requiresThreadLocalCleanup = true;
  }
  ComGoogleGsonGson_FutureTypeAdapter *ongoingCall = (ComGoogleGsonGson_FutureTypeAdapter *) check_class_cast([((id<JavaUtilMap>) nil_chk(threadCalls)) getWithId:type], [ComGoogleGsonGson_FutureTypeAdapter class]);
  if (ongoingCall != nil) {
    return ongoingCall;
  }
  @try {
    ComGoogleGsonGson_FutureTypeAdapter *call = [new_ComGoogleGsonGson_FutureTypeAdapter_init() autorelease];
    [threadCalls putWithId:type withId:call];
    for (id<ComGoogleGsonTypeAdapterFactory> __strong factory in nil_chk(factories_)) {
      ComGoogleGsonTypeAdapter *candidate = [((id<ComGoogleGsonTypeAdapterFactory>) nil_chk(factory)) createWithComGoogleGsonGson:self withComGoogleGsonReflectTypeToken:type];
      if (candidate != nil) {
        [call setDelegateWithComGoogleGsonTypeAdapter:candidate];
        [typeTokenCache_ putWithId:type withId:candidate];
        return candidate;
      }
    }
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$@", @"GSON cannot handle ", type)) autorelease];
  }
  @finally {
    [threadCalls removeWithId:type];
    if (requiresThreadLocalCleanup) {
      [calls_ remove];
    }
  }
}

- (ComGoogleGsonTypeAdapter *)getDelegateAdapterWithComGoogleGsonTypeAdapterFactory:(id<ComGoogleGsonTypeAdapterFactory>)skipPast
                                                  withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type {
  jboolean skipPastFound = false;
  if (![((id<JavaUtilList>) nil_chk(factories_)) containsWithId:skipPast]) skipPastFound = true;
  for (id<ComGoogleGsonTypeAdapterFactory> __strong factory in factories_) {
    if (!skipPastFound) {
      if (factory == skipPast) {
        skipPastFound = true;
      }
      continue;
    }
    ComGoogleGsonTypeAdapter *candidate = [((id<ComGoogleGsonTypeAdapterFactory>) nil_chk(factory)) createWithComGoogleGsonGson:self withComGoogleGsonReflectTypeToken:type];
    if (candidate != nil) {
      return candidate;
    }
  }
  @throw [new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("$@", @"GSON cannot serialize ", type)) autorelease];
}

- (ComGoogleGsonTypeAdapter *)getAdapterWithIOSClass:(IOSClass *)type {
  return [self getAdapterWithComGoogleGsonReflectTypeToken:ComGoogleGsonReflectTypeToken_getWithIOSClass_(type)];
}

- (ComGoogleGsonJsonElement *)toJsonTreeWithId:(id)src {
  if (src == nil) {
    return JreLoadStatic(ComGoogleGsonJsonNull, INSTANCE_);
  }
  return [self toJsonTreeWithId:src withJavaLangReflectType:[nil_chk(src) getClass]];
}

- (ComGoogleGsonJsonElement *)toJsonTreeWithId:(id)src
                       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc {
  ComGoogleGsonInternalBindJsonTreeWriter *writer = [new_ComGoogleGsonInternalBindJsonTreeWriter_init() autorelease];
  [self toJsonWithId:src withJavaLangReflectType:typeOfSrc withComGoogleGsonStreamJsonWriter:writer];
  return [writer get];
}

- (NSString *)toJsonWithId:(id)src {
  if (src == nil) {
    return [self toJsonWithComGoogleGsonJsonElement:JreLoadStatic(ComGoogleGsonJsonNull, INSTANCE_)];
  }
  return [self toJsonWithId:src withJavaLangReflectType:[nil_chk(src) getClass]];
}

- (NSString *)toJsonWithId:(id)src
   withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc {
  JavaIoStringWriter *writer = [new_JavaIoStringWriter_init() autorelease];
  [self toJsonWithId:src withJavaLangReflectType:typeOfSrc withJavaLangAppendable:writer];
  return [writer description];
}

- (void)toJsonWithId:(id)src
withJavaLangAppendable:(id<JavaLangAppendable>)writer {
  if (src != nil) {
    [self toJsonWithId:src withJavaLangReflectType:[src getClass] withJavaLangAppendable:writer];
  }
  else {
    [self toJsonWithComGoogleGsonJsonElement:JreLoadStatic(ComGoogleGsonJsonNull, INSTANCE_) withJavaLangAppendable:writer];
  }
}

- (void)toJsonWithId:(id)src
withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
withJavaLangAppendable:(id<JavaLangAppendable>)writer {
  @try {
    ComGoogleGsonStreamJsonWriter *jsonWriter = [self newJsonWriterWithJavaIoWriter:ComGoogleGsonInternalStreams_writerForAppendableWithJavaLangAppendable_(writer)];
    [self toJsonWithId:src withJavaLangReflectType:typeOfSrc withComGoogleGsonStreamJsonWriter:jsonWriter];
  }
  @catch (JavaIoIOException *e) {
    @throw [new_ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(e) autorelease];
  }
}

- (void)toJsonWithId:(id)src
withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc
withComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer {
  ComGoogleGsonTypeAdapter *adapter = [self getAdapterWithComGoogleGsonReflectTypeToken:ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(typeOfSrc)];
  jboolean oldLenient = [((ComGoogleGsonStreamJsonWriter *) nil_chk(writer)) isLenient];
  [writer setLenientWithBoolean:true];
  jboolean oldHtmlSafe = [writer isHtmlSafe];
  [writer setHtmlSafeWithBoolean:htmlSafe_];
  jboolean oldSerializeNulls = [writer getSerializeNulls];
  [writer setSerializeNullsWithBoolean:serializeNulls_];
  @try {
    [((ComGoogleGsonTypeAdapter *) nil_chk(((ComGoogleGsonTypeAdapter *) check_class_cast(adapter, [ComGoogleGsonTypeAdapter class])))) writeWithComGoogleGsonStreamJsonWriter:writer withId:src];
  }
  @catch (JavaIoIOException *e) {
    @throw [new_ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(e) autorelease];
  }
  @finally {
    [writer setLenientWithBoolean:oldLenient];
    [writer setHtmlSafeWithBoolean:oldHtmlSafe];
    [writer setSerializeNullsWithBoolean:oldSerializeNulls];
  }
}

- (NSString *)toJsonWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)jsonElement {
  JavaIoStringWriter *writer = [new_JavaIoStringWriter_init() autorelease];
  [self toJsonWithComGoogleGsonJsonElement:jsonElement withJavaLangAppendable:writer];
  return [writer description];
}

- (void)toJsonWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)jsonElement
                    withJavaLangAppendable:(id<JavaLangAppendable>)writer {
  @try {
    ComGoogleGsonStreamJsonWriter *jsonWriter = [self newJsonWriterWithJavaIoWriter:ComGoogleGsonInternalStreams_writerForAppendableWithJavaLangAppendable_(writer)];
    [self toJsonWithComGoogleGsonJsonElement:jsonElement withComGoogleGsonStreamJsonWriter:jsonWriter];
  }
  @catch (JavaIoIOException *e) {
    @throw [new_JavaLangRuntimeException_initWithJavaLangThrowable_(e) autorelease];
  }
}

- (ComGoogleGsonStreamJsonWriter *)newJsonWriterWithJavaIoWriter:(JavaIoWriter *)writer {
  if (generateNonExecutableJson_) {
    [((JavaIoWriter *) nil_chk(writer)) writeWithNSString:ComGoogleGsonGson_JSON_NON_EXECUTABLE_PREFIX_];
  }
  ComGoogleGsonStreamJsonWriter *jsonWriter = [new_ComGoogleGsonStreamJsonWriter_initWithJavaIoWriter_(writer) autorelease];
  if (prettyPrinting_) {
    [jsonWriter setIndentWithNSString:@"  "];
  }
  [jsonWriter setSerializeNullsWithBoolean:serializeNulls_];
  return jsonWriter;
}

- (void)toJsonWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)jsonElement
         withComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer {
  jboolean oldLenient = [((ComGoogleGsonStreamJsonWriter *) nil_chk(writer)) isLenient];
  [writer setLenientWithBoolean:true];
  jboolean oldHtmlSafe = [writer isHtmlSafe];
  [writer setHtmlSafeWithBoolean:htmlSafe_];
  jboolean oldSerializeNulls = [writer getSerializeNulls];
  [writer setSerializeNullsWithBoolean:serializeNulls_];
  @try {
    ComGoogleGsonInternalStreams_writeWithComGoogleGsonJsonElement_withComGoogleGsonStreamJsonWriter_(jsonElement, writer);
  }
  @catch (JavaIoIOException *e) {
    @throw [new_ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(e) autorelease];
  }
  @finally {
    [writer setLenientWithBoolean:oldLenient];
    [writer setHtmlSafeWithBoolean:oldHtmlSafe];
    [writer setSerializeNullsWithBoolean:oldSerializeNulls];
  }
}

- (id)fromJsonWithNSString:(NSString *)json
              withIOSClass:(IOSClass *)classOfT {
  id object = [self fromJsonWithNSString:json withJavaLangReflectType:classOfT];
  return [((IOSClass *) nil_chk(ComGoogleGsonInternalPrimitives_wrapWithIOSClass_(classOfT))) cast:object];
}

- (id)fromJsonWithNSString:(NSString *)json
   withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT {
  if (json == nil) {
    return nil;
  }
  JavaIoStringReader *reader = [new_JavaIoStringReader_initWithNSString_(json) autorelease];
  id target = (id) [self fromJsonWithJavaIoReader:reader withJavaLangReflectType:typeOfT];
  return target;
}

- (id)fromJsonWithJavaIoReader:(JavaIoReader *)json
                  withIOSClass:(IOSClass *)classOfT {
  ComGoogleGsonStreamJsonReader *jsonReader = [new_ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(json) autorelease];
  id object = [self fromJsonWithComGoogleGsonStreamJsonReader:jsonReader withJavaLangReflectType:classOfT];
  ComGoogleGsonGson_assertFullConsumptionWithId_withComGoogleGsonStreamJsonReader_(object, jsonReader);
  return [((IOSClass *) nil_chk(ComGoogleGsonInternalPrimitives_wrapWithIOSClass_(classOfT))) cast:object];
}

- (id)fromJsonWithJavaIoReader:(JavaIoReader *)json
       withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT {
  ComGoogleGsonStreamJsonReader *jsonReader = [new_ComGoogleGsonStreamJsonReader_initWithJavaIoReader_(json) autorelease];
  id object = (id) [self fromJsonWithComGoogleGsonStreamJsonReader:jsonReader withJavaLangReflectType:typeOfT];
  ComGoogleGsonGson_assertFullConsumptionWithId_withComGoogleGsonStreamJsonReader_(object, jsonReader);
  return object;
}

+ (void)assertFullConsumptionWithId:(id)obj
  withComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader {
  ComGoogleGsonGson_assertFullConsumptionWithId_withComGoogleGsonStreamJsonReader_(obj, reader);
}

- (id)fromJsonWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader
                        withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT {
  jboolean isEmpty = true;
  jboolean oldLenient = [((ComGoogleGsonStreamJsonReader *) nil_chk(reader)) isLenient];
  [reader setLenientWithBoolean:true];
  @try {
    [reader peek];
    isEmpty = false;
    ComGoogleGsonReflectTypeToken *typeToken = (ComGoogleGsonReflectTypeToken *) check_class_cast(ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(typeOfT), [ComGoogleGsonReflectTypeToken class]);
    ComGoogleGsonTypeAdapter *typeAdapter = [self getAdapterWithComGoogleGsonReflectTypeToken:typeToken];
    id object = [((ComGoogleGsonTypeAdapter *) nil_chk(typeAdapter)) readWithComGoogleGsonStreamJsonReader:reader];
    return object;
  }
  @catch (JavaIoEOFException *e) {
    if (isEmpty) {
      return nil;
    }
    @throw [new_ComGoogleGsonJsonSyntaxException_initWithJavaLangThrowable_(e) autorelease];
  }
  @catch (JavaLangIllegalStateException *e) {
    @throw [new_ComGoogleGsonJsonSyntaxException_initWithJavaLangThrowable_(e) autorelease];
  }
  @catch (JavaIoIOException *e) {
    @throw [new_ComGoogleGsonJsonSyntaxException_initWithJavaLangThrowable_(e) autorelease];
  }
  @finally {
    [reader setLenientWithBoolean:oldLenient];
  }
}

- (id)fromJsonWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                              withIOSClass:(IOSClass *)classOfT {
  id object = [self fromJsonWithComGoogleGsonJsonElement:json withJavaLangReflectType:classOfT];
  return [((IOSClass *) nil_chk(ComGoogleGsonInternalPrimitives_wrapWithIOSClass_(classOfT))) cast:object];
}

- (id)fromJsonWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                   withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT {
  if (json == nil) {
    return nil;
  }
  return (id) [self fromJsonWithComGoogleGsonStreamJsonReader:[new_ComGoogleGsonInternalBindJsonTreeReader_initWithComGoogleGsonJsonElement_(json) autorelease] withJavaLangReflectType:typeOfT];
}

- (NSString *)description {
  return [((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) nil_chk([((JavaLangStringBuilder *) [new_JavaLangStringBuilder_initWithNSString_(@"{serializeNulls:") autorelease]) appendWithBoolean:serializeNulls_])) appendWithNSString:@"factories:"])) appendWithId:factories_])) appendWithNSString:@",instanceCreators:"])) appendWithId:constructorConstructor_])) appendWithNSString:@"}"])) description];
}

- (void)dealloc {
  RELEASE_(calls_);
  RELEASE_(typeTokenCache_);
  RELEASE_(factories_);
  RELEASE_(constructorConstructor_);
  RELEASE_(deserializationContext_);
  RELEASE_(serializationContext_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Gson", NULL, 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalExcluder:withComGoogleGsonFieldNamingStrategy:withJavaUtilMap:withBoolean:withBoolean:withBoolean:withBoolean:withBoolean:withBoolean:withComGoogleGsonLongSerializationPolicyEnum:withJavaUtilList:", "Gson", NULL, 0x0, NULL, NULL },
    { "doubleAdapterWithBoolean:", "doubleAdapter", "Lcom.google.gson.TypeAdapter;", 0x2, NULL, NULL },
    { "floatAdapterWithBoolean:", "floatAdapter", "Lcom.google.gson.TypeAdapter;", 0x2, NULL, NULL },
    { "checkValidFloatingPointWithDouble:", "checkValidFloatingPoint", "V", 0x2, NULL, NULL },
    { "longAdapterWithComGoogleGsonLongSerializationPolicyEnum:", "longAdapter", "Lcom.google.gson.TypeAdapter;", 0x2, NULL, NULL },
    { "getAdapterWithComGoogleGsonReflectTypeToken:", "getAdapter", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "getDelegateAdapterWithComGoogleGsonTypeAdapterFactory:withComGoogleGsonReflectTypeToken:", "getDelegateAdapter", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/TypeAdapterFactory;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "getAdapterWithIOSClass:", "getAdapter", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Ljava/lang/Class<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "toJsonTreeWithId:", "toJsonTree", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "toJsonTreeWithId:withJavaLangReflectType:", "toJsonTree", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "toJsonWithId:", "toJson", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "toJsonWithId:withJavaLangReflectType:", "toJson", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "toJsonWithId:withJavaLangAppendable:", "toJson", "V", 0x1, "Lcom.google.gson.JsonIOException;", NULL },
    { "toJsonWithId:withJavaLangReflectType:withJavaLangAppendable:", "toJson", "V", 0x1, "Lcom.google.gson.JsonIOException;", NULL },
    { "toJsonWithId:withJavaLangReflectType:withComGoogleGsonStreamJsonWriter:", "toJson", "V", 0x1, "Lcom.google.gson.JsonIOException;", NULL },
    { "toJsonWithComGoogleGsonJsonElement:", "toJson", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "toJsonWithComGoogleGsonJsonElement:withJavaLangAppendable:", "toJson", "V", 0x1, "Lcom.google.gson.JsonIOException;", NULL },
    { "newJsonWriterWithJavaIoWriter:", "newJsonWriter", "Lcom.google.gson.stream.JsonWriter;", 0x1, "Ljava.io.IOException;", NULL },
    { "toJsonWithComGoogleGsonJsonElement:withComGoogleGsonStreamJsonWriter:", "toJson", "V", 0x1, "Lcom.google.gson.JsonIOException;", NULL },
    { "fromJsonWithNSString:withIOSClass:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Ljava/lang/String;Ljava/lang/Class<TT;>;)TT;" },
    { "fromJsonWithNSString:withJavaLangReflectType:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Ljava/lang/String;Ljava/lang/reflect/Type;)TT;" },
    { "fromJsonWithJavaIoReader:withIOSClass:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonSyntaxException;Lcom.google.gson.JsonIOException;", "<T:Ljava/lang/Object;>(Ljava/io/Reader;Ljava/lang/Class<TT;>;)TT;" },
    { "fromJsonWithJavaIoReader:withJavaLangReflectType:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonIOException;Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Ljava/io/Reader;Ljava/lang/reflect/Type;)TT;" },
    { "assertFullConsumptionWithId:withComGoogleGsonStreamJsonReader:", "assertFullConsumption", "V", 0xa, NULL, NULL },
    { "fromJsonWithComGoogleGsonStreamJsonReader:withJavaLangReflectType:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonIOException;Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Lcom/google/gson/stream/JsonReader;Ljava/lang/reflect/Type;)TT;" },
    { "fromJsonWithComGoogleGsonJsonElement:withIOSClass:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Lcom/google/gson/JsonElement;Ljava/lang/Class<TT;>;)TT;" },
    { "fromJsonWithComGoogleGsonJsonElement:withJavaLangReflectType:", "fromJson", "TT;", 0x1, "Lcom.google.gson.JsonSyntaxException;", "<T:Ljava/lang/Object;>(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;)TT;" },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DEFAULT_JSON_NON_EXECUTABLE", "DEFAULT_JSON_NON_EXECUTABLE", 0x18, "Z", NULL, NULL, .constantValue.asBOOL = ComGoogleGsonGson_DEFAULT_JSON_NON_EXECUTABLE },
    { "JSON_NON_EXECUTABLE_PREFIX_", NULL, 0x1a, "Ljava.lang.String;", &ComGoogleGsonGson_JSON_NON_EXECUTABLE_PREFIX_, NULL, .constantValue.asLong = 0 },
    { "calls_", NULL, 0x12, "Ljava.lang.ThreadLocal;", NULL, "Ljava/lang/ThreadLocal<Ljava/util/Map<Lcom/google/gson/reflect/TypeToken<*>;Lcom/google/gson/Gson$FutureTypeAdapter<*>;>;>;", .constantValue.asLong = 0 },
    { "typeTokenCache_", NULL, 0x12, "Ljava.util.Map;", NULL, "Ljava/util/Map<Lcom/google/gson/reflect/TypeToken<*>;Lcom/google/gson/TypeAdapter<*>;>;", .constantValue.asLong = 0 },
    { "factories_", NULL, 0x12, "Ljava.util.List;", NULL, "Ljava/util/List<Lcom/google/gson/TypeAdapterFactory;>;", .constantValue.asLong = 0 },
    { "constructorConstructor_", NULL, 0x12, "Lcom.google.gson.internal.ConstructorConstructor;", NULL, NULL, .constantValue.asLong = 0 },
    { "serializeNulls_", NULL, 0x12, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "htmlSafe_", NULL, 0x12, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "generateNonExecutableJson_", NULL, 0x12, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "prettyPrinting_", NULL, 0x12, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "deserializationContext_", NULL, 0x10, "Lcom.google.gson.JsonDeserializationContext;", NULL, NULL, .constantValue.asLong = 0 },
    { "serializationContext_", NULL, 0x10, "Lcom.google.gson.JsonSerializationContext;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lcom.google.gson.Gson$FutureTypeAdapter;"};
  static const J2ObjcClassInfo _ComGoogleGsonGson = { 2, "Gson", "com.google.gson", NULL, 0x11, 29, methods, 12, fields, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_ComGoogleGsonGson;
}

@end

void ComGoogleGsonGson_init(ComGoogleGsonGson *self) {
  ComGoogleGsonGson_initWithComGoogleGsonInternalExcluder_withComGoogleGsonFieldNamingStrategy_withJavaUtilMap_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withComGoogleGsonLongSerializationPolicyEnum_withJavaUtilList_(self, JreLoadStatic(ComGoogleGsonInternalExcluder, DEFAULT_), JreLoadStatic(ComGoogleGsonFieldNamingPolicyEnum, IDENTITY), JavaUtilCollections_emptyMap(), false, false, ComGoogleGsonGson_DEFAULT_JSON_NON_EXECUTABLE, true, false, false, JreLoadStatic(ComGoogleGsonLongSerializationPolicyEnum, DEFAULT), JavaUtilCollections_emptyList());
}

ComGoogleGsonGson *new_ComGoogleGsonGson_init() {
  ComGoogleGsonGson *self = [ComGoogleGsonGson alloc];
  ComGoogleGsonGson_init(self);
  return self;
}

void ComGoogleGsonGson_initWithComGoogleGsonInternalExcluder_withComGoogleGsonFieldNamingStrategy_withJavaUtilMap_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withComGoogleGsonLongSerializationPolicyEnum_withJavaUtilList_(ComGoogleGsonGson *self, ComGoogleGsonInternalExcluder *excluder, id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy, id<JavaUtilMap> instanceCreators, jboolean serializeNulls, jboolean complexMapKeySerialization, jboolean generateNonExecutableGson, jboolean htmlSafe, jboolean prettyPrinting, jboolean serializeSpecialFloatingPointValues, ComGoogleGsonLongSerializationPolicyEnum *longSerializationPolicy, id<JavaUtilList> typeAdapterFactories) {
  NSObject_init(self);
  JreStrongAssignAndConsume(&self->calls_, new_JavaLangThreadLocal_init());
  JreStrongAssign(&self->typeTokenCache_, JavaUtilCollections_synchronizedMapWithJavaUtilMap_([new_JavaUtilHashMap_init() autorelease]));
  JreStrongAssignAndConsume(&self->deserializationContext_, new_ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(self));
  JreStrongAssignAndConsume(&self->serializationContext_, new_ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(self));
  JreStrongAssignAndConsume(&self->constructorConstructor_, new_ComGoogleGsonInternalConstructorConstructor_initWithJavaUtilMap_(instanceCreators));
  self->serializeNulls_ = serializeNulls;
  self->generateNonExecutableJson_ = generateNonExecutableGson;
  self->htmlSafe_ = htmlSafe;
  self->prettyPrinting_ = prettyPrinting;
  id<JavaUtilList> factories = [new_JavaUtilArrayList_init() autorelease];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, JSON_ELEMENT_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindObjectTypeAdapter, FACTORY_)];
  [factories addWithId:excluder];
  [factories addAllWithJavaUtilCollection:typeAdapterFactories];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, STRING_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, INTEGER_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, BOOLEAN_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, BYTE_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, SHORT_FACTORY_)];
  [factories addWithId:ComGoogleGsonInternalBindTypeAdapters_newFactoryWithIOSClass_withIOSClass_withComGoogleGsonTypeAdapter_([IOSClass longClass], JavaLangLong_class_(), ComGoogleGsonGson_longAdapterWithComGoogleGsonLongSerializationPolicyEnum_(self, longSerializationPolicy))];
  [factories addWithId:ComGoogleGsonInternalBindTypeAdapters_newFactoryWithIOSClass_withIOSClass_withComGoogleGsonTypeAdapter_([IOSClass doubleClass], JavaLangDouble_class_(), ComGoogleGsonGson_doubleAdapterWithBoolean_(self, serializeSpecialFloatingPointValues))];
  [factories addWithId:ComGoogleGsonInternalBindTypeAdapters_newFactoryWithIOSClass_withIOSClass_withComGoogleGsonTypeAdapter_([IOSClass floatClass], JavaLangFloat_class_(), ComGoogleGsonGson_floatAdapterWithBoolean_(self, serializeSpecialFloatingPointValues))];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, NUMBER_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, CHARACTER_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, STRING_BUILDER_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, STRING_BUFFER_FACTORY_)];
  [factories addWithId:ComGoogleGsonInternalBindTypeAdapters_newFactoryWithIOSClass_withComGoogleGsonTypeAdapter_(JavaMathBigDecimal_class_(), JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, BIG_DECIMAL_))];
  [factories addWithId:ComGoogleGsonInternalBindTypeAdapters_newFactoryWithIOSClass_withComGoogleGsonTypeAdapter_(JavaMathBigInteger_class_(), JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, BIG_INTEGER_))];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, URL_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, URI_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, UUID_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, LOCALE_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, INET_ADDRESS_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, BIT_SET_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindDateTypeAdapter, FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, CALENDAR_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTimeTypeAdapter, FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindSqlDateTypeAdapter, FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, TIMESTAMP_FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindArrayTypeAdapter, FACTORY_)];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, CLASS_FACTORY_)];
  [factories addWithId:[new_ComGoogleGsonInternalBindCollectionTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(self->constructorConstructor_) autorelease]];
  [factories addWithId:[new_ComGoogleGsonInternalBindMapTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withBoolean_(self->constructorConstructor_, complexMapKeySerialization) autorelease]];
  [factories addWithId:[new_ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_(self->constructorConstructor_) autorelease]];
  [factories addWithId:JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, ENUM_FACTORY_)];
  [factories addWithId:[new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonFieldNamingStrategy_withComGoogleGsonInternalExcluder_(self->constructorConstructor_, fieldNamingPolicy, excluder) autorelease]];
  JreStrongAssign(&self->factories_, JavaUtilCollections_unmodifiableListWithJavaUtilList_(factories));
}

ComGoogleGsonGson *new_ComGoogleGsonGson_initWithComGoogleGsonInternalExcluder_withComGoogleGsonFieldNamingStrategy_withJavaUtilMap_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withComGoogleGsonLongSerializationPolicyEnum_withJavaUtilList_(ComGoogleGsonInternalExcluder *excluder, id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy, id<JavaUtilMap> instanceCreators, jboolean serializeNulls, jboolean complexMapKeySerialization, jboolean generateNonExecutableGson, jboolean htmlSafe, jboolean prettyPrinting, jboolean serializeSpecialFloatingPointValues, ComGoogleGsonLongSerializationPolicyEnum *longSerializationPolicy, id<JavaUtilList> typeAdapterFactories) {
  ComGoogleGsonGson *self = [ComGoogleGsonGson alloc];
  ComGoogleGsonGson_initWithComGoogleGsonInternalExcluder_withComGoogleGsonFieldNamingStrategy_withJavaUtilMap_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withBoolean_withComGoogleGsonLongSerializationPolicyEnum_withJavaUtilList_(self, excluder, fieldNamingPolicy, instanceCreators, serializeNulls, complexMapKeySerialization, generateNonExecutableGson, htmlSafe, prettyPrinting, serializeSpecialFloatingPointValues, longSerializationPolicy, typeAdapterFactories);
  return self;
}

ComGoogleGsonTypeAdapter *ComGoogleGsonGson_doubleAdapterWithBoolean_(ComGoogleGsonGson *self, jboolean serializeSpecialFloatingPointValues) {
  if (serializeSpecialFloatingPointValues) {
    return JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, DOUBLE_);
  }
  return [new_ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(self) autorelease];
}

ComGoogleGsonTypeAdapter *ComGoogleGsonGson_floatAdapterWithBoolean_(ComGoogleGsonGson *self, jboolean serializeSpecialFloatingPointValues) {
  if (serializeSpecialFloatingPointValues) {
    return JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, FLOAT_);
  }
  return [new_ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(self) autorelease];
}

void ComGoogleGsonGson_checkValidFloatingPointWithDouble_(ComGoogleGsonGson *self, jdouble value) {
  if (JavaLangDouble_isNaNWithDouble_(value) || JavaLangDouble_isInfiniteWithDouble_(value)) {
    @throw [new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("D$", value, @" is not a valid double value as per JSON specification. To override this behavior, use GsonBuilder.serializeSpecialFloatingPointValues() method.")) autorelease];
  }
}

ComGoogleGsonTypeAdapter *ComGoogleGsonGson_longAdapterWithComGoogleGsonLongSerializationPolicyEnum_(ComGoogleGsonGson *self, ComGoogleGsonLongSerializationPolicyEnum *longSerializationPolicy) {
  if (longSerializationPolicy == JreLoadStatic(ComGoogleGsonLongSerializationPolicyEnum, DEFAULT)) {
    return JreLoadStatic(ComGoogleGsonInternalBindTypeAdapters, LONG_);
  }
  return [new_ComGoogleGsonGson_$5_init() autorelease];
}

void ComGoogleGsonGson_assertFullConsumptionWithId_withComGoogleGsonStreamJsonReader_(id obj, ComGoogleGsonStreamJsonReader *reader) {
  ComGoogleGsonGson_initialize();
  @try {
    if (obj != nil && [((ComGoogleGsonStreamJsonReader *) nil_chk(reader)) peek] != JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, END_DOCUMENT)) {
      @throw [new_ComGoogleGsonJsonIOException_initWithNSString_(@"JSON document was not fully consumed.") autorelease];
    }
  }
  @catch (ComGoogleGsonStreamMalformedJsonException *e) {
    @throw [new_ComGoogleGsonJsonSyntaxException_initWithJavaLangThrowable_(e) autorelease];
  }
  @catch (JavaIoIOException *e) {
    @throw [new_ComGoogleGsonJsonIOException_initWithJavaLangThrowable_(e) autorelease];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson)

@implementation ComGoogleGsonGson_FutureTypeAdapter

- (void)setDelegateWithComGoogleGsonTypeAdapter:(ComGoogleGsonTypeAdapter *)typeAdapter {
  if (delegate_ != nil) {
    @throw [new_JavaLangAssertionError_init() autorelease];
  }
  JreStrongAssign(&delegate_, typeAdapter);
}

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if (delegate_ == nil) {
    @throw [new_JavaLangIllegalStateException_init() autorelease];
  }
  return [((ComGoogleGsonTypeAdapter *) nil_chk(delegate_)) readWithComGoogleGsonStreamJsonReader:inArg];
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value {
  if (delegate_ == nil) {
    @throw [new_JavaLangIllegalStateException_init() autorelease];
  }
  [((ComGoogleGsonTypeAdapter *) nil_chk(delegate_)) writeWithComGoogleGsonStreamJsonWriter:outArg withId:value];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonGson_FutureTypeAdapter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(delegate_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setDelegateWithComGoogleGsonTypeAdapter:", "setDelegate", "V", 0x1, NULL, NULL },
    { "readWithComGoogleGsonStreamJsonReader:", "read", "TT;", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonReader;)TT;" },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonWriter;TT;)V" },
    { "init", NULL, NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "delegate_", NULL, 0x2, "Lcom.google.gson.TypeAdapter;", NULL, "Lcom/google/gson/TypeAdapter<TT;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const J2ObjcClassInfo _ComGoogleGsonGson_FutureTypeAdapter = { 2, "FutureTypeAdapter", "com.google.gson", "Gson", 0x8, 4, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "<T:Ljava/lang/Object;>Lcom/google/gson/TypeAdapter<TT;>;" };
  return &_ComGoogleGsonGson_FutureTypeAdapter;
}

@end

void ComGoogleGsonGson_FutureTypeAdapter_init(ComGoogleGsonGson_FutureTypeAdapter *self) {
  ComGoogleGsonTypeAdapter_init(self);
}

ComGoogleGsonGson_FutureTypeAdapter *new_ComGoogleGsonGson_FutureTypeAdapter_init() {
  ComGoogleGsonGson_FutureTypeAdapter *self = [ComGoogleGsonGson_FutureTypeAdapter alloc];
  ComGoogleGsonGson_FutureTypeAdapter_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_FutureTypeAdapter)

@implementation ComGoogleGsonGson_$1

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT {
  return (id) [this$0_ fromJsonWithComGoogleGsonJsonElement:json withJavaLangReflectType:typeOfT];
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$ {
  ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:", "deserialize", "TT;", 0x1, "Lcom.google.gson.JsonParseException;", "<T:Ljava/lang/Object;>(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;)TT;" },
    { "initWithComGoogleGsonGson:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonGson_$1 = { 2, "", "com.google.gson", "Gson", 0x8008, 2, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonGson_$1;
}

@end

void ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(ComGoogleGsonGson_$1 *self, ComGoogleGsonGson *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

ComGoogleGsonGson_$1 *new_ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) {
  ComGoogleGsonGson_$1 *self = [ComGoogleGsonGson_$1 alloc];
  ComGoogleGsonGson_$1_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_$1)

@implementation ComGoogleGsonGson_$2

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src {
  return [this$0_ toJsonTreeWithId:src];
}

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc {
  return [this$0_ toJsonTreeWithId:src withJavaLangReflectType:typeOfSrc];
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$ {
  ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "serializeWithId:", "serialize", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "serializeWithId:withJavaLangReflectType:", "serialize", "Lcom.google.gson.JsonElement;", 0x1, NULL, NULL },
    { "initWithComGoogleGsonGson:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonGson_$2 = { 2, "", "com.google.gson", "Gson", 0x8008, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonGson_$2;
}

@end

void ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(ComGoogleGsonGson_$2 *self, ComGoogleGsonGson *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
}

ComGoogleGsonGson_$2 *new_ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) {
  ComGoogleGsonGson_$2 *self = [ComGoogleGsonGson_$2 alloc];
  ComGoogleGsonGson_$2_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_$2)

@implementation ComGoogleGsonGson_$3

- (JavaLangDouble *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if ([((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek] == JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, NULL)) {
    [inArg nextNull];
    return nil;
  }
  return JavaLangDouble_valueOfWithDouble_([inArg nextDouble]);
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value {
  if (value == nil) {
    [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  jdouble doubleValue = [((NSNumber *) nil_chk(value)) doubleValue];
  ComGoogleGsonGson_checkValidFloatingPointWithDouble_(this$0_, doubleValue);
  [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) valueWithNSNumber:value];
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$ {
  ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "readWithComGoogleGsonStreamJsonReader:", "read", "Ljava.lang.Double;", 0x1, "Ljava.io.IOException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "initWithComGoogleGsonGson:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Number;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonGson", "doubleAdapterWithBoolean:" };
  static const J2ObjcClassInfo _ComGoogleGsonGson_$3 = { 2, "", "com.google.gson", "Gson", 0x8008, 3, methods, 1, fields, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/TypeAdapter<Ljava/lang/Number;>;" };
  return &_ComGoogleGsonGson_$3;
}

@end

void ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(ComGoogleGsonGson_$3 *self, ComGoogleGsonGson *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  ComGoogleGsonTypeAdapter_init(self);
}

ComGoogleGsonGson_$3 *new_ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) {
  ComGoogleGsonGson_$3 *self = [ComGoogleGsonGson_$3 alloc];
  ComGoogleGsonGson_$3_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_$3)

@implementation ComGoogleGsonGson_$4

- (JavaLangFloat *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if ([((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek] == JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, NULL)) {
    [inArg nextNull];
    return nil;
  }
  return JavaLangFloat_valueOfWithFloat_((jfloat) [inArg nextDouble]);
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value {
  if (value == nil) {
    [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  jfloat floatValue = [((NSNumber *) nil_chk(value)) floatValue];
  ComGoogleGsonGson_checkValidFloatingPointWithDouble_(this$0_, floatValue);
  [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) valueWithNSNumber:value];
}

- (instancetype)initWithComGoogleGsonGson:(ComGoogleGsonGson *)outer$ {
  ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "readWithComGoogleGsonStreamJsonReader:", "read", "Ljava.lang.Float;", 0x1, "Ljava.io.IOException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "initWithComGoogleGsonGson:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Number;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonGson", "floatAdapterWithBoolean:" };
  static const J2ObjcClassInfo _ComGoogleGsonGson_$4 = { 2, "", "com.google.gson", "Gson", 0x8008, 3, methods, 1, fields, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/TypeAdapter<Ljava/lang/Number;>;" };
  return &_ComGoogleGsonGson_$4;
}

@end

void ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(ComGoogleGsonGson_$4 *self, ComGoogleGsonGson *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  ComGoogleGsonTypeAdapter_init(self);
}

ComGoogleGsonGson_$4 *new_ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(ComGoogleGsonGson *outer$) {
  ComGoogleGsonGson_$4 *self = [ComGoogleGsonGson_$4 alloc];
  ComGoogleGsonGson_$4_initWithComGoogleGsonGson_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_$4)

@implementation ComGoogleGsonGson_$5

- (NSNumber *)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if ([((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek] == JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, NULL)) {
    [inArg nextNull];
    return nil;
  }
  return JavaLangLong_valueOfWithLong_([inArg nextLong]);
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(NSNumber *)value {
  if (value == nil) {
    [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) valueWithNSString:[((NSNumber *) nil_chk(value)) description]];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonGson_$5_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "readWithComGoogleGsonStreamJsonReader:", "read", "Ljava.lang.Number;", 0x1, "Ljava.io.IOException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.lang.Number;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonGson", "longAdapterWithComGoogleGsonLongSerializationPolicyEnum:" };
  static const J2ObjcClassInfo _ComGoogleGsonGson_$5 = { 2, "", "com.google.gson", "Gson", 0x8008, 3, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/TypeAdapter<Ljava/lang/Number;>;" };
  return &_ComGoogleGsonGson_$5;
}

@end

void ComGoogleGsonGson_$5_init(ComGoogleGsonGson_$5 *self) {
  ComGoogleGsonTypeAdapter_init(self);
}

ComGoogleGsonGson_$5 *new_ComGoogleGsonGson_$5_init() {
  ComGoogleGsonGson_$5 *self = [ComGoogleGsonGson_$5 alloc];
  ComGoogleGsonGson_$5_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonGson_$5)
