//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/InstanceCreator.java
//

#ifndef _InstanceCreator_H_
#define _InstanceCreator_H_

#include "J2ObjC_header.h"

@protocol JavaLangReflectType;

@protocol ComGoogleGsonInstanceCreator < NSObject, JavaObject >

- (id)createInstanceWithJavaLangReflectType:(id<JavaLangReflectType>)type;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInstanceCreator)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInstanceCreator)

#endif // _InstanceCreator_H_
