//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonDeserializationContext.java
//

#ifndef _JsonDeserializationContext_H_
#define _JsonDeserializationContext_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@protocol JavaLangReflectType;

@protocol ComGoogleGsonJsonDeserializationContext < NSObject, JavaObject >

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonDeserializationContext)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonDeserializationContext)

#endif // _JsonDeserializationContext_H_
