//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonDeserializer.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "JsonDeserializationContext.h"
#include "JsonDeserializer.h"
#include "JsonElement.h"
#include "JsonParseException.h"
#include "java/lang/reflect/Type.h"

@interface ComGoogleGsonJsonDeserializer : NSObject

@end

@implementation ComGoogleGsonJsonDeserializer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "deserializeWithComGoogleGsonJsonElement:withJavaLangReflectType:withComGoogleGsonJsonDeserializationContext:", "deserialize", "TT;", 0x401, "Lcom.google.gson.JsonParseException;", "(Lcom/google/gson/JsonElement;Ljava/lang/reflect/Type;Lcom/google/gson/JsonDeserializationContext;)TT;" },
  };
  static const J2ObjcClassInfo _ComGoogleGsonJsonDeserializer = { 2, "JsonDeserializer", "com.google.gson", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComGoogleGsonJsonDeserializer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonJsonDeserializer)
