//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonParser.java
//

#ifndef _JsonParser_H_
#define _JsonParser_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class JavaIoReader;

@interface ComGoogleGsonJsonParser : NSObject

#pragma mark Public

- (instancetype)init;

- (ComGoogleGsonJsonElement *)parseWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)json;

- (ComGoogleGsonJsonElement *)parseWithJavaIoReader:(JavaIoReader *)json;

- (ComGoogleGsonJsonElement *)parseWithNSString:(NSString *)json;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonParser)

FOUNDATION_EXPORT void ComGoogleGsonJsonParser_init(ComGoogleGsonJsonParser *self);

FOUNDATION_EXPORT ComGoogleGsonJsonParser *new_ComGoogleGsonJsonParser_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonParser)

#endif // _JsonParser_H_
