//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/stream/JsonWriter.java
//

#ifndef _JsonWriter_H_
#define _JsonWriter_H_

#include "J2ObjC_header.h"
#include "java/io/Closeable.h"
#include "java/io/Flushable.h"

@class JavaIoWriter;

@interface ComGoogleGsonStreamJsonWriter : NSObject < JavaIoCloseable, JavaIoFlushable >

#pragma mark Public

- (instancetype)initWithJavaIoWriter:(JavaIoWriter *)outArg;

- (ComGoogleGsonStreamJsonWriter *)beginArray;

- (ComGoogleGsonStreamJsonWriter *)beginObject;

- (void)close;

- (ComGoogleGsonStreamJsonWriter *)endArray;

- (ComGoogleGsonStreamJsonWriter *)endObject;

- (void)flush;

- (jboolean)getSerializeNulls;

- (jboolean)isHtmlSafe;

- (jboolean)isLenient;

- (ComGoogleGsonStreamJsonWriter *)jsonValueWithNSString:(NSString *)value;

- (ComGoogleGsonStreamJsonWriter *)nameWithNSString:(NSString *)name;

- (ComGoogleGsonStreamJsonWriter *)nullValue;

- (void)setHtmlSafeWithBoolean:(jboolean)htmlSafe;

- (void)setIndentWithNSString:(NSString *)indent;

- (void)setLenientWithBoolean:(jboolean)lenient;

- (void)setSerializeNullsWithBoolean:(jboolean)serializeNulls;

- (ComGoogleGsonStreamJsonWriter *)valueWithBoolean:(jboolean)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithDouble:(jdouble)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithLong:(jlong)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithNSNumber:(NSNumber *)value;

- (ComGoogleGsonStreamJsonWriter *)valueWithNSString:(NSString *)value;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonStreamJsonWriter)

FOUNDATION_EXPORT void ComGoogleGsonStreamJsonWriter_initWithJavaIoWriter_(ComGoogleGsonStreamJsonWriter *self, JavaIoWriter *outArg);

FOUNDATION_EXPORT ComGoogleGsonStreamJsonWriter *new_ComGoogleGsonStreamJsonWriter_initWithJavaIoWriter_(JavaIoWriter *outArg) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonStreamJsonWriter)

#endif // _JsonWriter_H_
