//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/JsonReaderInternalAccess.java
//

#ifndef _JsonReaderInternalAccess_H_
#define _JsonReaderInternalAccess_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonStreamJsonReader;

@interface ComGoogleGsonInternalJsonReaderInternalAccess : NSObject

#pragma mark Public

- (instancetype)init;

- (void)promoteNameToValueWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalJsonReaderInternalAccess)

FOUNDATION_EXPORT ComGoogleGsonInternalJsonReaderInternalAccess *ComGoogleGsonInternalJsonReaderInternalAccess_INSTANCE_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonInternalJsonReaderInternalAccess, INSTANCE_, ComGoogleGsonInternalJsonReaderInternalAccess *)
J2OBJC_STATIC_FIELD_SETTER(ComGoogleGsonInternalJsonReaderInternalAccess, INSTANCE_, ComGoogleGsonInternalJsonReaderInternalAccess *)

FOUNDATION_EXPORT void ComGoogleGsonInternalJsonReaderInternalAccess_init(ComGoogleGsonInternalJsonReaderInternalAccess *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalJsonReaderInternalAccess)

#endif // _JsonReaderInternalAccess_H_
