//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonObject.java
//

#ifndef _JsonObject_H_
#define _JsonObject_H_

#include "J2ObjC_header.h"
#include "JsonElement.h"

@class ComGoogleGsonJsonArray;
@class ComGoogleGsonJsonPrimitive;
@class JavaLangBoolean;
@class JavaLangCharacter;
@protocol JavaUtilSet;

@interface ComGoogleGsonJsonObject : ComGoogleGsonJsonElement

#pragma mark Public

- (instancetype)init;

- (void)addWithNSString:(NSString *)property
withComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)value;

- (void)addPropertyWithNSString:(NSString *)property
            withJavaLangBoolean:(JavaLangBoolean *)value;

- (void)addPropertyWithNSString:(NSString *)property
          withJavaLangCharacter:(JavaLangCharacter *)value;

- (void)addPropertyWithNSString:(NSString *)property
                   withNSNumber:(NSNumber *)value;

- (void)addPropertyWithNSString:(NSString *)property
                   withNSString:(NSString *)value;

- (id<JavaUtilSet>)entrySet;

- (jboolean)isEqual:(id)o;

- (ComGoogleGsonJsonElement *)getWithNSString:(NSString *)memberName;

- (ComGoogleGsonJsonArray *)getAsJsonArrayWithNSString:(NSString *)memberName;

- (ComGoogleGsonJsonObject *)getAsJsonObjectWithNSString:(NSString *)memberName;

- (ComGoogleGsonJsonPrimitive *)getAsJsonPrimitiveWithNSString:(NSString *)memberName;

- (jboolean)hasWithNSString:(NSString *)memberName;

- (NSUInteger)hash;

- (ComGoogleGsonJsonElement *)removeWithNSString:(NSString *)property;

#pragma mark Package-Private

- (ComGoogleGsonJsonObject *)deepCopy;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonObject)

FOUNDATION_EXPORT void ComGoogleGsonJsonObject_init(ComGoogleGsonJsonObject *self);

FOUNDATION_EXPORT ComGoogleGsonJsonObject *new_ComGoogleGsonJsonObject_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonObject)

#endif // _JsonObject_H_
