//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonStreamParser.java
//

#ifndef _JsonStreamParser_H_
#define _JsonStreamParser_H_

#include "J2ObjC_header.h"
#include "java/util/Iterator.h"

@class ComGoogleGsonJsonElement;
@class JavaIoReader;

@interface ComGoogleGsonJsonStreamParser : NSObject < JavaUtilIterator >

#pragma mark Public

- (instancetype)initWithJavaIoReader:(JavaIoReader *)reader;

- (instancetype)initWithNSString:(NSString *)json;

- (jboolean)hasNext;

- (ComGoogleGsonJsonElement *)next;

- (void)remove;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonStreamParser)

FOUNDATION_EXPORT void ComGoogleGsonJsonStreamParser_initWithNSString_(ComGoogleGsonJsonStreamParser *self, NSString *json);

FOUNDATION_EXPORT ComGoogleGsonJsonStreamParser *new_ComGoogleGsonJsonStreamParser_initWithNSString_(NSString *json) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonJsonStreamParser_initWithJavaIoReader_(ComGoogleGsonJsonStreamParser *self, JavaIoReader *reader);

FOUNDATION_EXPORT ComGoogleGsonJsonStreamParser *new_ComGoogleGsonJsonStreamParser_initWithJavaIoReader_(JavaIoReader *reader) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonStreamParser)

#endif // _JsonStreamParser_H_
