//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonDeserializer.java
//

#ifndef _JsonDeserializer_H_
#define _JsonDeserializer_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@protocol ComGoogleGsonJsonDeserializationContext;
@protocol JavaLangReflectType;

@protocol ComGoogleGsonJsonDeserializer < NSObject, JavaObject >

- (id)deserializeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)json
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfT
  withComGoogleGsonJsonDeserializationContext:(id<ComGoogleGsonJsonDeserializationContext>)context;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonDeserializer)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonDeserializer)

#endif // _JsonDeserializer_H_
