//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonElement.java
//

#ifndef _JsonElement_H_
#define _JsonElement_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonArray;
@class ComGoogleGsonJsonNull;
@class ComGoogleGsonJsonObject;
@class ComGoogleGsonJsonPrimitive;
@class JavaLangBoolean;
@class JavaMathBigDecimal;
@class JavaMathBigInteger;

@interface ComGoogleGsonJsonElement : NSObject

#pragma mark Public

- (instancetype)init;

- (JavaMathBigDecimal *)getAsBigDecimal;

- (JavaMathBigInteger *)getAsBigInteger;

- (jboolean)getAsBoolean;

- (jbyte)getAsByte;

- (jchar)getAsCharacter;

- (jdouble)getAsDouble;

- (jfloat)getAsFloat;

- (jint)getAsInt;

- (ComGoogleGsonJsonArray *)getAsJsonArray;

- (ComGoogleGsonJsonNull *)getAsJsonNull;

- (ComGoogleGsonJsonObject *)getAsJsonObject;

- (ComGoogleGsonJsonPrimitive *)getAsJsonPrimitive;

- (jlong)getAsLong;

- (NSNumber *)getAsNumber;

- (jshort)getAsShort;

- (NSString *)getAsString;

- (jboolean)isJsonArray;

- (jboolean)isJsonNull;

- (jboolean)isJsonObject;

- (jboolean)isJsonPrimitive;

- (NSString *)description;

#pragma mark Package-Private

- (ComGoogleGsonJsonElement *)deepCopy;

- (JavaLangBoolean *)getAsBooleanWrapper;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonElement)

FOUNDATION_EXPORT void ComGoogleGsonJsonElement_init(ComGoogleGsonJsonElement *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonElement)

#endif // _JsonElement_H_
