//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/JsonSerializationContext.java
//

#ifndef _JsonSerializationContext_H_
#define _JsonSerializationContext_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@protocol JavaLangReflectType;

@protocol ComGoogleGsonJsonSerializationContext < NSObject, JavaObject >

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src;

- (ComGoogleGsonJsonElement *)serializeWithId:(id)src
                      withJavaLangReflectType:(id<JavaLangReflectType>)typeOfSrc;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonJsonSerializationContext)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonJsonSerializationContext)

#endif // _JsonSerializationContext_H_
