//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/LazilyParsedNumber.java
//

#ifndef _LazilyParsedNumber_H_
#define _LazilyParsedNumber_H_

#include "J2ObjC_header.h"

@interface ComGoogleGsonInternalLazilyParsedNumber : NSNumber

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)value;

- (jdouble)doubleValue;

- (jboolean)isEqual:(id)obj;

- (jfloat)floatValue;

- (NSUInteger)hash;

- (jint)intValue;

- (jlong)longLongValue;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLazilyParsedNumber)

FOUNDATION_EXPORT void ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(ComGoogleGsonInternalLazilyParsedNumber *self, NSString *value);

FOUNDATION_EXPORT ComGoogleGsonInternalLazilyParsedNumber *new_ComGoogleGsonInternalLazilyParsedNumber_initWithNSString_(NSString *value) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLazilyParsedNumber)

#endif // _LazilyParsedNumber_H_
