//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/LinkedHashTreeMap.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "LinkedHashTreeMap.h"
#include "java/io/ObjectStreamException.h"
#include "java/lang/ClassCastException.h"
#include "java/lang/Comparable.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/Integer.h"
#include "java/lang/Math.h"
#include "java/lang/NullPointerException.h"
#include "java/util/AbstractMap.h"
#include "java/util/AbstractSet.h"
#include "java/util/Arrays.h"
#include "java/util/Comparator.h"
#include "java/util/ConcurrentModificationException.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "java/util/NoSuchElementException.h"
#include "java/util/Set.h"

#pragma clang diagnostic ignored "-Wprotocol"

@interface ComGoogleGsonInternalLinkedHashTreeMap () {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *entrySet_;
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet *keySet_LinkedHashTreeMap_;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b;

+ (jint)secondaryHashWithInt:(jint)h;

- (void)replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node
                       withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)replacement;

- (void)rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)unbalanced
                                                     withBoolean:(jboolean)insert;

- (void)rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root;

- (void)rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root;

- (void)doubleCapacity;

- (id)writeReplace;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap, entrySet_, ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap, keySet_LinkedHashTreeMap_, ComGoogleGsonInternalLinkedHashTreeMap_KeySet *)

static id<JavaUtilComparator> ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_;
J2OBJC_STATIC_FIELD_GETTER(ComGoogleGsonInternalLinkedHashTreeMap, NATURAL_ORDER_, id<JavaUtilComparator>)

__attribute__((unused)) static jboolean ComGoogleGsonInternalLinkedHashTreeMap_equalWithId_withId_(ComGoogleGsonInternalLinkedHashTreeMap *self, id a, id b);

__attribute__((unused)) static jint ComGoogleGsonInternalLinkedHashTreeMap_secondaryHashWithInt_(jint h);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *node, ComGoogleGsonInternalLinkedHashTreeMap_Node *replacement);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node_withBoolean_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *unbalanced, jboolean insert);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *root);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *root);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacity(ComGoogleGsonInternalLinkedHashTreeMap *self);

@interface ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator () {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap_Node *stackTop_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator, stackTop_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)

@interface ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder () {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap_Node *stack_;
  jint leavesToSkip_;
  jint leavesSkipped_;
  jint size_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder, stack_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)

@interface ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator : NSObject < JavaUtilIterator > {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap *this$0_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *next_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *lastReturned_;
  jint expectedModCount_;
}

- (jboolean)hasNext;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)nextNode;

- (void)remove;

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator, this$0_, ComGoogleGsonInternalLinkedHashTreeMap *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator, next_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator, lastReturned_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)

__attribute__((unused)) static ComGoogleGsonInternalLinkedHashTreeMap_Node *ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_nextNode(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator *self);

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator)

@interface ComGoogleGsonInternalLinkedHashTreeMap_EntrySet () {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet, this$0_, ComGoogleGsonInternalLinkedHashTreeMap *)

@interface ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 : ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator

- (id<JavaUtilMap_Entry>)next;

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet:(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 *self, ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *outer$);

__attribute__((unused)) static ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1)

@interface ComGoogleGsonInternalLinkedHashTreeMap_KeySet () {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap *this$0_;
}

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_KeySet, this$0_, ComGoogleGsonInternalLinkedHashTreeMap *)

@interface ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 : ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator

- (id)next;

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet:(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *)outer$;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 *self, ComGoogleGsonInternalLinkedHashTreeMap_KeySet *outer$);

__attribute__((unused)) static ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1)

@interface ComGoogleGsonInternalLinkedHashTreeMap_$1 : NSObject < JavaUtilComparator >

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_$1)

__attribute__((unused)) static void ComGoogleGsonInternalLinkedHashTreeMap_$1_init(ComGoogleGsonInternalLinkedHashTreeMap_$1 *self);

__attribute__((unused)) static ComGoogleGsonInternalLinkedHashTreeMap_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_$1_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_$1)

J2OBJC_INITIALIZED_DEFN(ComGoogleGsonInternalLinkedHashTreeMap)

@implementation ComGoogleGsonInternalLinkedHashTreeMap

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternalLinkedHashTreeMap_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator {
  ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

- (jint)size {
  return size_;
}

- (id)getWithId:(id)key {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = [self findByObjectWithId:key];
  return node != nil ? node->value_ : nil;
}

- (jboolean)containsKeyWithId:(id)key {
  return [self findByObjectWithId:key] != nil;
}

- (id)putWithId:(id)key
         withId:(id)value {
  if (key == nil) {
    @throw [new_JavaLangNullPointerException_initWithNSString_(@"key == null") autorelease];
  }
  ComGoogleGsonInternalLinkedHashTreeMap_Node *created = [self findWithId:key withBoolean:true];
  id result = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(created))->value_;
  JreStrongAssign(&created->value_, value);
  return result;
}

- (void)clear {
  JavaUtilArrays_fillWithNSObjectArray_withId_(table_, nil);
  size_ = 0;
  modCount_++;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *header = self->header_;
  for (ComGoogleGsonInternalLinkedHashTreeMap_Node *e = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(header))->next_; e != header; ) {
    ComGoogleGsonInternalLinkedHashTreeMap_Node *next = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(e))->next_;
    JreStrongAssign(&e->next_, JreStrongAssign(&e->prev_, nil));
    e = next;
  }
  JreStrongAssign(&header->next_, JreStrongAssign(&header->prev_, header));
}

- (id)removeWithId:(id)key {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = [self removeInternalByKeyWithId:key];
  return node != nil ? node->value_ : nil;
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findWithId:(id)key
                                                withBoolean:(jboolean)create {
  id<JavaUtilComparator> comparator = self->comparator_;
  IOSObjectArray *table = self->table_;
  jint hash_ = ComGoogleGsonInternalLinkedHashTreeMap_secondaryHashWithInt_(((jint) [nil_chk(key) hash]));
  jint index = hash_ & (((IOSObjectArray *) nil_chk(table))->size_ - 1);
  ComGoogleGsonInternalLinkedHashTreeMap_Node *nearest = IOSObjectArray_Get(table, index);
  jint comparison = 0;
  if (nearest != nil) {
    id<JavaLangComparable> comparableKey = (comparator == ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_) ? (id<JavaLangComparable>) check_protocol_cast(key, JavaLangComparable_class_()) : nil;
    while (true) {
      comparison = (comparableKey != nil) ? [comparableKey compareToWithId:nearest->key_] : [((id<JavaUtilComparator>) nil_chk(comparator)) compareWithId:key withId:nearest->key_];
      if (comparison == 0) {
        return nearest;
      }
      ComGoogleGsonInternalLinkedHashTreeMap_Node *child = (comparison < 0) ? nearest->left_ : nearest->right_;
      if (child == nil) {
        break;
      }
      nearest = child;
    }
  }
  if (!create) {
    return nil;
  }
  ComGoogleGsonInternalLinkedHashTreeMap_Node *header = self->header_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *created;
  if (nearest == nil) {
    if (comparator == ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_ && !([JavaLangComparable_class_() isInstance:key])) {
      @throw [new_JavaLangClassCastException_initWithNSString_(JreStrcat("$$", [[key getClass] getName], @" is not Comparable")) autorelease];
    }
    created = [new_ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(nearest, key, hash_, header, ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(header))->prev_) autorelease];
    IOSObjectArray_Set(table, index, created);
  }
  else {
    created = [new_ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(nearest, key, hash_, header, ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(header))->prev_) autorelease];
    if (comparison < 0) {
      JreStrongAssign(&nearest->left_, created);
    }
    else {
      JreStrongAssign(&nearest->right_, created);
    }
    ComGoogleGsonInternalLinkedHashTreeMap_rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node_withBoolean_(self, nearest, true);
  }
  if (size_++ > threshold_) {
    ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacity(self);
  }
  modCount_++;
  return created;
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findByObjectWithId:(id)key {
  @try {
    return key != nil ? [self findWithId:(id) key withBoolean:false] : nil;
  }
  @catch (JavaLangClassCastException *e) {
    return nil;
  }
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_ {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *mine = [self findByObjectWithId:[((id<JavaUtilMap_Entry>) nil_chk(entry_)) getKey]];
  jboolean valuesEqual = mine != nil && ComGoogleGsonInternalLinkedHashTreeMap_equalWithId_withId_(self, mine->value_, [entry_ getValue]);
  return valuesEqual ? mine : nil;
}

- (jboolean)equalWithId:(id)a
                 withId:(id)b {
  return ComGoogleGsonInternalLinkedHashTreeMap_equalWithId_withId_(self, a, b);
}

+ (jint)secondaryHashWithInt:(jint)h {
  return ComGoogleGsonInternalLinkedHashTreeMap_secondaryHashWithInt_(h);
}

- (void)removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node
                                                          withBoolean:(jboolean)unlink {
  if (unlink) {
    JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->prev_))->next_, node->next_);
    JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node->next_))->prev_, node->prev_);
    JreStrongAssign(&node->next_, JreStrongAssign(&node->prev_, nil));
  }
  ComGoogleGsonInternalLinkedHashTreeMap_Node *left = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *right = node->right_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *originalParent = node->parent_;
  if (left != nil && right != nil) {
    ComGoogleGsonInternalLinkedHashTreeMap_Node *adjacent = (left->height_ > right->height_) ? [left last] : [right first];
    [self removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:adjacent withBoolean:false];
    jint leftHeight = 0;
    left = node->left_;
    if (left != nil) {
      leftHeight = left->height_;
      JreStrongAssign(&adjacent->left_, left);
      JreStrongAssign(&left->parent_, adjacent);
      JreStrongAssign(&node->left_, nil);
    }
    jint rightHeight = 0;
    right = node->right_;
    if (right != nil) {
      rightHeight = right->height_;
      JreStrongAssign(&adjacent->right_, right);
      JreStrongAssign(&right->parent_, adjacent);
      JreStrongAssign(&node->right_, nil);
    }
    adjacent->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
    ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node, adjacent);
    return;
  }
  else if (left != nil) {
    ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node, left);
    JreStrongAssign(&node->left_, nil);
  }
  else if (right != nil) {
    ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node, right);
    JreStrongAssign(&node->right_, nil);
  }
  else {
    ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node, nil);
  }
  ComGoogleGsonInternalLinkedHashTreeMap_rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node_withBoolean_(self, originalParent, false);
  size_--;
  modCount_++;
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)removeInternalByKeyWithId:(id)key {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = [self findByObjectWithId:key];
  if (node != nil) {
    [self removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:node withBoolean:true];
  }
  return node;
}

- (void)replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node
                       withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)replacement {
  ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node, replacement);
}

- (void)rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)unbalanced
                                                     withBoolean:(jboolean)insert {
  ComGoogleGsonInternalLinkedHashTreeMap_rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node_withBoolean_(self, unbalanced, insert);
}

- (void)rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, root);
}

- (void)rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, root);
}

- (id<JavaUtilSet>)entrySet {
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *result = entrySet_;
  return result != nil ? result : (JreStrongAssignAndConsume(&entrySet_, new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self)));
}

- (id<JavaUtilSet>)keySet {
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet *result = keySet_LinkedHashTreeMap_;
  return result != nil ? result : (JreStrongAssignAndConsume(&keySet_LinkedHashTreeMap_, new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self)));
}

- (void)doubleCapacity {
  ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacity(self);
}

+ (IOSObjectArray *)doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray:(IOSObjectArray *)oldTable {
  return ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray_(oldTable);
}

- (id)writeReplace {
  return [new_JavaUtilLinkedHashMap_initWithJavaUtilMap_(self) autorelease];
}

- (void)dealloc {
  RELEASE_(comparator_);
  RELEASE_(table_);
  RELEASE_(header_);
  RELEASE_(entrySet_);
  RELEASE_(keySet_LinkedHashTreeMap_);
  [super dealloc];
}

+ (void)initialize {
  if (self == [ComGoogleGsonInternalLinkedHashTreeMap class]) {
    JreStrongAssignAndConsume(&ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_, new_ComGoogleGsonInternalLinkedHashTreeMap_$1_init());
    J2OBJC_SET_INITIALIZED(ComGoogleGsonInternalLinkedHashTreeMap)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "LinkedHashTreeMap", NULL, 0x1, NULL, NULL },
    { "initWithJavaUtilComparator:", "LinkedHashTreeMap", NULL, 0x1, NULL, NULL },
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "getWithId:", "get", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "containsKeyWithId:", "containsKey", "Z", 0x1, NULL, NULL },
    { "putWithId:withId:", "put", "TV;", 0x1, NULL, "(TK;TV;)TV;" },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "TV;", 0x1, NULL, "(Ljava/lang/Object;)TV;" },
    { "findWithId:withBoolean:", "find", "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x0, NULL, "(TK;Z)Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;" },
    { "findByObjectWithId:", "findByObject", "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x0, NULL, NULL },
    { "findByEntryWithJavaUtilMap_Entry:", "findByEntry", "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x0, NULL, NULL },
    { "equalWithId:withId:", "equal", "Z", 0x2, NULL, NULL },
    { "secondaryHashWithInt:", "secondaryHash", "I", 0xa, NULL, NULL },
    { "removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:withBoolean:", "removeInternal", "V", 0x0, NULL, NULL },
    { "removeInternalByKeyWithId:", "removeInternalByKey", "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x0, NULL, NULL },
    { "replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node:withComGoogleGsonInternalLinkedHashTreeMap_Node:", "replaceInParent", "V", 0x2, NULL, NULL },
    { "rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node:withBoolean:", "rebalance", "V", 0x2, NULL, NULL },
    { "rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node:", "rotateLeft", "V", 0x2, NULL, NULL },
    { "rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node:", "rotateRight", "V", 0x2, NULL, NULL },
    { "entrySet", NULL, "Ljava.util.Set;", 0x1, NULL, NULL },
    { "keySet", NULL, "Ljava.util.Set;", 0x1, NULL, NULL },
    { "doubleCapacity", NULL, "V", 0x2, NULL, NULL },
    { "doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray:", "doubleCapacity", "[Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x8, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>([Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;)[Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;" },
    { "writeReplace", NULL, "Ljava.lang.Object;", 0x2, "Ljava.io.ObjectStreamException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NATURAL_ORDER_", NULL, 0x1a, "Ljava.util.Comparator;", &ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_, "Ljava/util/Comparator<Ljava/lang/Comparable;>;", .constantValue.asLong = 0 },
    { "comparator_", NULL, 0x0, "Ljava.util.Comparator;", NULL, "Ljava/util/Comparator<-TK;>;", .constantValue.asLong = 0 },
    { "table_", NULL, 0x0, "[Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "[Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "header_", NULL, 0x10, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "size_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "modCount_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "threshold_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "entrySet_", NULL, 0x2, "Lcom.google.gson.internal.LinkedHashTreeMap$EntrySet;", NULL, NULL, .constantValue.asLong = 0 },
    { "keySet_LinkedHashTreeMap_", "keySet", 0x2, "Lcom.google.gson.internal.LinkedHashTreeMap$KeySet;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TK;", "TV;"};
  static const char *inner_classes[] = {"Lcom.google.gson.internal.LinkedHashTreeMap$Node;", "Lcom.google.gson.internal.LinkedHashTreeMap$AvlIterator;", "Lcom.google.gson.internal.LinkedHashTreeMap$AvlBuilder;", "Lcom.google.gson.internal.LinkedHashTreeMap$LinkedTreeMapIterator;", "Lcom.google.gson.internal.LinkedHashTreeMap$EntrySet;", "Lcom.google.gson.internal.LinkedHashTreeMap$KeySet;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap = { 2, "LinkedHashTreeMap", "com.google.gson.internal", NULL, 0x11, 24, methods, 9, fields, 2, superclass_type_args, 6, inner_classes, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/util/AbstractMap<TK;TV;>;Ljava/io/Serializable;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_init(ComGoogleGsonInternalLinkedHashTreeMap *self) {
  ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(self, (id<JavaUtilComparator>) check_protocol_cast(ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_, JavaUtilComparator_class_()));
}

ComGoogleGsonInternalLinkedHashTreeMap *new_ComGoogleGsonInternalLinkedHashTreeMap_init() {
  ComGoogleGsonInternalLinkedHashTreeMap *self = [ComGoogleGsonInternalLinkedHashTreeMap alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_init(self);
  return self;
}

void ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(ComGoogleGsonInternalLinkedHashTreeMap *self, id<JavaUtilComparator> comparator) {
  JavaUtilAbstractMap_init(self);
  self->size_ = 0;
  self->modCount_ = 0;
  JreStrongAssign(&self->comparator_, comparator != nil ? ((id) comparator) : ((id) ComGoogleGsonInternalLinkedHashTreeMap_NATURAL_ORDER_));
  JreStrongAssignAndConsume(&self->header_, new_ComGoogleGsonInternalLinkedHashTreeMap_Node_init());
  JreStrongAssignAndConsume(&self->table_, [IOSObjectArray newArrayWithLength:16 type:ComGoogleGsonInternalLinkedHashTreeMap_Node_class_()]);
  self->threshold_ = (self->table_->size_ / 2) + (self->table_->size_ / 4);
}

ComGoogleGsonInternalLinkedHashTreeMap *new_ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) {
  ComGoogleGsonInternalLinkedHashTreeMap *self = [ComGoogleGsonInternalLinkedHashTreeMap alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(self, comparator);
  return self;
}

jboolean ComGoogleGsonInternalLinkedHashTreeMap_equalWithId_withId_(ComGoogleGsonInternalLinkedHashTreeMap *self, id a, id b) {
  return a == b || (a != nil && [a isEqual:b]);
}

jint ComGoogleGsonInternalLinkedHashTreeMap_secondaryHashWithInt_(jint h) {
  ComGoogleGsonInternalLinkedHashTreeMap_initialize();
  h ^= (JreURShift32(h, 20)) ^ (JreURShift32(h, 12));
  return h ^ (JreURShift32(h, 7)) ^ (JreURShift32(h, 4));
}

void ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *node, ComGoogleGsonInternalLinkedHashTreeMap_Node *replacement) {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *parent = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->parent_;
  JreStrongAssign(&node->parent_, nil);
  if (replacement != nil) {
    JreStrongAssign(&replacement->parent_, parent);
  }
  if (parent != nil) {
    if (parent->left_ == node) {
      JreStrongAssign(&parent->left_, replacement);
    }
    else {
      JreAssert((parent->right_ == node), (@"com/google/gson/internal/LinkedHashTreeMap.java:322 condition failed: assert (parent.right == node);"));
      JreStrongAssign(&parent->right_, replacement);
    }
  }
  else {
    jint index = node->hash__ & (((IOSObjectArray *) nil_chk(self->table_))->size_ - 1);
    IOSObjectArray_Set(self->table_, index, replacement);
  }
}

void ComGoogleGsonInternalLinkedHashTreeMap_rebalanceWithComGoogleGsonInternalLinkedHashTreeMap_Node_withBoolean_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *unbalanced, jboolean insert) {
  for (ComGoogleGsonInternalLinkedHashTreeMap_Node *node = unbalanced; node != nil; node = node->parent_) {
    ComGoogleGsonInternalLinkedHashTreeMap_Node *left = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->left_;
    ComGoogleGsonInternalLinkedHashTreeMap_Node *right = node->right_;
    jint leftHeight = left != nil ? left->height_ : 0;
    jint rightHeight = right != nil ? right->height_ : 0;
    jint delta = leftHeight - rightHeight;
    if (delta == -2) {
      ComGoogleGsonInternalLinkedHashTreeMap_Node *rightLeft = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(right))->left_;
      ComGoogleGsonInternalLinkedHashTreeMap_Node *rightRight = right->right_;
      jint rightRightHeight = rightRight != nil ? rightRight->height_ : 0;
      jint rightLeftHeight = rightLeft != nil ? rightLeft->height_ : 0;
      jint rightDelta = rightLeftHeight - rightRightHeight;
      if (rightDelta == -1 || (rightDelta == 0 && !insert)) {
        ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node);
      }
      else {
        JreAssert((rightDelta == 1), (@"com/google/gson/internal/LinkedHashTreeMap.java:356 condition failed: assert (rightDelta == 1);"));
        ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, right);
        ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 2) {
      ComGoogleGsonInternalLinkedHashTreeMap_Node *leftLeft = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(left))->left_;
      ComGoogleGsonInternalLinkedHashTreeMap_Node *leftRight = left->right_;
      jint leftRightHeight = leftRight != nil ? leftRight->height_ : 0;
      jint leftLeftHeight = leftLeft != nil ? leftLeft->height_ : 0;
      jint leftDelta = leftLeftHeight - leftRightHeight;
      if (leftDelta == 1 || (leftDelta == 0 && !insert)) {
        ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node);
      }
      else {
        JreAssert((leftDelta == -1), (@"com/google/gson/internal/LinkedHashTreeMap.java:374 condition failed: assert (leftDelta == -1);"));
        ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, left);
        ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(self, node);
      }
      if (insert) {
        break;
      }
    }
    else if (delta == 0) {
      node->height_ = leftHeight + 1;
      if (insert) {
        break;
      }
    }
    else {
      JreAssert(((delta == -1 || delta == 1)), (@"com/google/gson/internal/LinkedHashTreeMap.java:389 condition failed: assert (delta == -1 || delta == 1);"));
      node->height_ = JavaLangMath_maxWithInt_withInt_(leftHeight, rightHeight) + 1;
      if (!insert) {
        break;
      }
    }
  }
}

void ComGoogleGsonInternalLinkedHashTreeMap_rotateLeftWithComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *root) {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *left = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(root))->left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivot = root->right_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivotLeft = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(pivot))->left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivotRight = pivot->right_;
  JreStrongAssign(&root->right_, pivotLeft);
  if (pivotLeft != nil) {
    JreStrongAssign(&pivotLeft->parent_, root);
  }
  ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, root, pivot);
  JreStrongAssign(&pivot->left_, root);
  JreStrongAssign(&root->parent_, pivot);
  root->height_ = JavaLangMath_maxWithInt_withInt_(left != nil ? left->height_ : 0, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotRight != nil ? pivotRight->height_ : 0) + 1;
}

void ComGoogleGsonInternalLinkedHashTreeMap_rotateRightWithComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *root) {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivot = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(root))->left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *right = root->right_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivotLeft = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(pivot))->left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *pivotRight = pivot->right_;
  JreStrongAssign(&root->left_, pivotRight);
  if (pivotRight != nil) {
    JreStrongAssign(&pivotRight->parent_, root);
  }
  ComGoogleGsonInternalLinkedHashTreeMap_replaceInParentWithComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, root, pivot);
  JreStrongAssign(&pivot->right_, root);
  JreStrongAssign(&root->parent_, pivot);
  root->height_ = JavaLangMath_maxWithInt_withInt_(right != nil ? right->height_ : 0, pivotRight != nil ? pivotRight->height_ : 0) + 1;
  pivot->height_ = JavaLangMath_maxWithInt_withInt_(root->height_, pivotLeft != nil ? pivotLeft->height_ : 0) + 1;
}

void ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacity(ComGoogleGsonInternalLinkedHashTreeMap *self) {
  JreStrongAssign(&self->table_, ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray_(self->table_));
  self->threshold_ = (((IOSObjectArray *) nil_chk(self->table_))->size_ / 2) + (self->table_->size_ / 4);
}

IOSObjectArray *ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray_(IOSObjectArray *oldTable) {
  ComGoogleGsonInternalLinkedHashTreeMap_initialize();
  jint oldCapacity = ((IOSObjectArray *) nil_chk(oldTable))->size_;
  IOSObjectArray *newTable = [IOSObjectArray arrayWithLength:oldCapacity * 2 type:ComGoogleGsonInternalLinkedHashTreeMap_Node_class_()];
  ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *iterator = [new_ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init() autorelease];
  ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *leftBuilder = [new_ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init() autorelease];
  ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *rightBuilder = [new_ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init() autorelease];
  for (jint i = 0; i < oldCapacity; i++) {
    ComGoogleGsonInternalLinkedHashTreeMap_Node *root = IOSObjectArray_Get(oldTable, i);
    if (root == nil) {
      continue;
    }
    [iterator resetWithComGoogleGsonInternalLinkedHashTreeMap_Node:root];
    jint leftSize = 0;
    jint rightSize = 0;
    for (ComGoogleGsonInternalLinkedHashTreeMap_Node *node; (node = [iterator next]) != nil; ) {
      if ((((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->hash__ & oldCapacity) == 0) {
        leftSize++;
      }
      else {
        rightSize++;
      }
    }
    [leftBuilder resetWithInt:leftSize];
    [rightBuilder resetWithInt:rightSize];
    [iterator resetWithComGoogleGsonInternalLinkedHashTreeMap_Node:root];
    for (ComGoogleGsonInternalLinkedHashTreeMap_Node *node; (node = [iterator next]) != nil; ) {
      if ((((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->hash__ & oldCapacity) == 0) {
        [leftBuilder addWithComGoogleGsonInternalLinkedHashTreeMap_Node:node];
      }
      else {
        [rightBuilder addWithComGoogleGsonInternalLinkedHashTreeMap_Node:node];
      }
    }
    IOSObjectArray_Set(newTable, i, leftSize > 0 ? [leftBuilder root] : nil);
    IOSObjectArray_Set(newTable, i + oldCapacity, rightSize > 0 ? [rightBuilder root] : nil);
  }
  return newTable;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_Node

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternalLinkedHashTreeMap_Node_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)parent
                                                             withId:(id)key
                                                            withInt:(jint)hash_
                    withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)next
                    withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)prev {
  ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, parent, key, hash_, next, prev);
  return self;
}

- (id)getKey {
  return key_;
}

- (id)getValue {
  return value_;
}

- (id)setValueWithId:(id)value {
  id oldValue = self->value_;
  JreStrongAssign(&self->value_, value);
  return oldValue;
}

- (jboolean)isEqual:(id)o {
  if ([JavaUtilMap_Entry_class_() isInstance:o]) {
    id<JavaUtilMap_Entry> other = (id<JavaUtilMap_Entry>) check_protocol_cast(o, JavaUtilMap_Entry_class_());
    return (key_ == nil ? [((id<JavaUtilMap_Entry>) nil_chk(other)) getKey] == nil : [key_ isEqual:[((id<JavaUtilMap_Entry>) nil_chk(other)) getKey]]) && (value_ == nil ? [other getValue] == nil : [value_ isEqual:[other getValue]]);
  }
  return false;
}

- (NSUInteger)hash {
  return (key_ == nil ? 0 : ((jint) [key_ hash])) ^ (value_ == nil ? 0 : ((jint) [value_ hash]));
}

- (NSString *)description {
  return JreStrcat("@C@", key_, '=', value_);
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)first {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = self;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *child = node->left_;
  while (child != nil) {
    node = child;
    child = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->left_;
  }
  return node;
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)last {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = self;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *child = node->right_;
  while (child != nil) {
    node = child;
    child = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->right_;
  }
  return node;
}

- (void)dealloc {
  RELEASE_(parent_);
  RELEASE_(left_);
  RELEASE_(right_);
  RELEASE_(next_);
  RELEASE_(prev_);
  RELEASE_(key_);
  RELEASE_(value_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Node", NULL, 0x0, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap_Node:withId:withInt:withComGoogleGsonInternalLinkedHashTreeMap_Node:withComGoogleGsonInternalLinkedHashTreeMap_Node:", "Node", NULL, 0x0, NULL, "(Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;TK;ILcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;)V" },
    { "getKey", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "getValue", NULL, "TV;", 0x1, NULL, "()TV;" },
    { "setValueWithId:", "setValue", "TV;", 0x1, NULL, "(TV;)TV;" },
    { "isEqual:", "equals", "Z", 0x1, NULL, NULL },
    { "hash", "hashCode", "I", 0x1, NULL, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL, NULL },
    { "first", NULL, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x1, NULL, NULL },
    { "last", NULL, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "parent_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "left_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "right_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "prev_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "key_", NULL, 0x10, "TK;", NULL, "TK;", .constantValue.asLong = 0 },
    { "hash__", "hash", 0x10, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "value_", NULL, 0x0, "TV;", NULL, "TV;", .constantValue.asLong = 0 },
    { "height_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_Node = { 2, "Node", "com.google.gson.internal", "LinkedHashTreeMap", 0x18, 10, methods, 9, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Map$Entry<TK;TV;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_Node;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_Node_init(ComGoogleGsonInternalLinkedHashTreeMap_Node *self) {
  NSObject_init(self);
  JreStrongAssign(&self->key_, nil);
  self->hash__ = -1;
  JreStrongAssign(&self->next_, JreStrongAssign(&self->prev_, self));
}

ComGoogleGsonInternalLinkedHashTreeMap_Node *new_ComGoogleGsonInternalLinkedHashTreeMap_Node_init() {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *self = [ComGoogleGsonInternalLinkedHashTreeMap_Node alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_Node_init(self);
  return self;
}

void ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap_Node *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *parent, id key, jint hash_, ComGoogleGsonInternalLinkedHashTreeMap_Node *next, ComGoogleGsonInternalLinkedHashTreeMap_Node *prev) {
  NSObject_init(self);
  JreStrongAssign(&self->parent_, parent);
  JreStrongAssign(&self->key_, key);
  self->hash__ = hash_;
  self->height_ = 1;
  JreStrongAssign(&self->next_, next);
  JreStrongAssign(&self->prev_, prev);
  JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(prev))->next_, self);
  JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(next))->prev_, self);
}

ComGoogleGsonInternalLinkedHashTreeMap_Node *new_ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap_Node *parent, id key, jint hash_, ComGoogleGsonInternalLinkedHashTreeMap_Node *next, ComGoogleGsonInternalLinkedHashTreeMap_Node *prev) {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *self = [ComGoogleGsonInternalLinkedHashTreeMap_Node alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(self, parent, key, hash_, next, prev);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_Node)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator

- (void)resetWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *stackTop = nil;
  for (ComGoogleGsonInternalLinkedHashTreeMap_Node *n = root; n != nil; n = n->left_) {
    JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(n))->parent_, stackTop);
    stackTop = n;
  }
  JreStrongAssign(&self->stackTop_, stackTop);
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)next {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *stackTop = self->stackTop_;
  if (stackTop == nil) {
    return nil;
  }
  ComGoogleGsonInternalLinkedHashTreeMap_Node *result = stackTop;
  stackTop = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(result))->parent_;
  JreStrongAssign(&result->parent_, nil);
  for (ComGoogleGsonInternalLinkedHashTreeMap_Node *n = result->right_; n != nil; n = n->left_) {
    JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(n))->parent_, stackTop);
    stackTop = n;
  }
  JreStrongAssign(&self->stackTop_, stackTop);
  return result;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(stackTop_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "resetWithComGoogleGsonInternalLinkedHashTreeMap_Node:", "reset", "V", 0x0, NULL, NULL },
    { "next", NULL, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "stackTop_", NULL, 0x2, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator = { 2, "AvlIterator", "com.google.gson.internal", "LinkedHashTreeMap", 0x8, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *self) {
  NSObject_init(self);
}

ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *new_ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init() {
  ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *self = [ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder

- (void)resetWithInt:(jint)targetSize {
  jint treeCapacity = JavaLangInteger_highestOneBitWithInt_(targetSize) * 2 - 1;
  leavesToSkip_ = treeCapacity - targetSize;
  size_ = 0;
  leavesSkipped_ = 0;
  JreStrongAssign(&stack_, nil);
}

- (void)addWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node {
  JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(node))->left_, JreStrongAssign(&node->parent_, JreStrongAssign(&node->right_, nil)));
  node->height_ = 1;
  if (leavesToSkip_ > 0 && (size_ & 1) == 0) {
    size_++;
    leavesToSkip_--;
    leavesSkipped_++;
  }
  JreStrongAssign(&node->parent_, stack_);
  JreStrongAssign(&stack_, node);
  size_++;
  if (leavesToSkip_ > 0 && (size_ & 1) == 0) {
    size_++;
    leavesToSkip_--;
    leavesSkipped_++;
  }
  for (jint scale_ = 4; (size_ & (scale_ - 1)) == scale_ - 1; scale_ *= 2) {
    if (leavesSkipped_ == 0) {
      ComGoogleGsonInternalLinkedHashTreeMap_Node *right = stack_;
      ComGoogleGsonInternalLinkedHashTreeMap_Node *center = right->parent_;
      ComGoogleGsonInternalLinkedHashTreeMap_Node *left = ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(center))->parent_;
      JreStrongAssign(&center->parent_, ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(left))->parent_);
      JreStrongAssign(&stack_, center);
      JreStrongAssign(&center->left_, left);
      JreStrongAssign(&center->right_, right);
      center->height_ = right->height_ + 1;
      JreStrongAssign(&left->parent_, center);
      JreStrongAssign(&right->parent_, center);
    }
    else if (leavesSkipped_ == 1) {
      ComGoogleGsonInternalLinkedHashTreeMap_Node *right = stack_;
      ComGoogleGsonInternalLinkedHashTreeMap_Node *center = right->parent_;
      JreStrongAssign(&stack_, center);
      JreStrongAssign(&((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(center))->right_, right);
      center->height_ = right->height_ + 1;
      JreStrongAssign(&right->parent_, center);
      leavesSkipped_ = 0;
    }
    else if (leavesSkipped_ == 2) {
      leavesSkipped_ = 0;
    }
  }
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)root {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *stackTop = self->stack_;
  if (((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(stackTop))->parent_ != nil) {
    @throw [new_JavaLangIllegalStateException_init() autorelease];
  }
  return stackTop;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)dealloc {
  RELEASE_(stack_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "resetWithInt:", "reset", "V", 0x0, NULL, NULL },
    { "addWithComGoogleGsonInternalLinkedHashTreeMap_Node:", "add", "V", 0x0, NULL, NULL },
    { "root", NULL, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x0, NULL, NULL },
    { "init", NULL, NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "stack_", NULL, 0x2, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "leavesToSkip_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "leavesSkipped_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
    { "size_", NULL, 0x2, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder = { 2, "AvlBuilder", "com.google.gson.internal", "LinkedHashTreeMap", 0x18, 4, methods, 4, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *self) {
  NSObject_init(self);
}

ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *new_ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init() {
  ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *self = [ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator

- (jboolean)hasNext {
  return next_ != this$0_->header_;
}

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)nextNode {
  return ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (void)remove {
  if (lastReturned_ == nil) {
    @throw [new_JavaLangIllegalStateException_init() autorelease];
  }
  [this$0_ removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:lastReturned_ withBoolean:true];
  JreStrongAssign(&lastReturned_, nil);
  expectedModCount_ = this$0_->modCount_;
}

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(next_);
  RELEASE_(lastReturned_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasNext", NULL, "Z", 0x11, NULL, NULL },
    { "nextNode", NULL, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", 0x10, NULL, NULL },
    { "remove", NULL, "V", 0x11, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedHashTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
    { "next_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "lastReturned_", NULL, 0x0, "Lcom.google.gson.internal.LinkedHashTreeMap$Node;", NULL, "Lcom/google/gson/internal/LinkedHashTreeMap$Node<TK;TV;>;", .constantValue.asLong = 0 },
    { "expectedModCount_", NULL, 0x0, "I", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator = { 2, "LinkedTreeMapIterator", "com.google.gson.internal", "LinkedHashTreeMap", 0x402, 4, methods, 4, fields, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljava/util/Iterator<TT;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator;
}

@end

ComGoogleGsonInternalLinkedHashTreeMap_Node *ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_nextNode(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator *self) {
  ComGoogleGsonInternalLinkedHashTreeMap_Node *e = self->next_;
  if (e == self->this$0_->header_) {
    @throw [new_JavaUtilNoSuchElementException_init() autorelease];
  }
  if (self->this$0_->modCount_ != self->expectedModCount_) {
    @throw [new_JavaUtilConcurrentModificationException_init() autorelease];
  }
  JreStrongAssign(&self->next_, ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(e))->next_);
  return JreStrongAssign(&self->lastReturned_, e);
}

void ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  NSObject_init(self);
  JreStrongAssign(&self->next_, ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(outer$->header_))->next_);
  JreStrongAssign(&self->lastReturned_, nil);
  self->expectedModCount_ = outer$->modCount_;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_EntrySet

- (jint)size {
  return this$0_->size_;
}

- (id<JavaUtilIterator>)iterator {
  return [new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(self) autorelease];
}

- (jboolean)containsWithId:(id)o {
  return [JavaUtilMap_Entry_class_() isInstance:o] && [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) check_protocol_cast(o, JavaUtilMap_Entry_class_())] != nil;
}

- (jboolean)removeWithId:(id)o {
  if (!([JavaUtilMap_Entry_class_() isInstance:o])) {
    return false;
  }
  ComGoogleGsonInternalLinkedHashTreeMap_Node *node = [this$0_ findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>) check_protocol_cast(o, JavaUtilMap_Entry_class_())];
  if (node == nil) {
    return false;
  }
  [this$0_ removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:node withBoolean:true];
  return true;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedHashTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_EntrySet = { 2, "EntrySet", "com.google.gson.internal", "LinkedHashTreeMap", 0x10, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  JavaUtilAbstractSet_init(self);
}

ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *self = [ComGoogleGsonInternalLinkedHashTreeMap_EntrySet alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1

- (id<JavaUtilMap_Entry>)next {
  return ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_nextNode(self);
}

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet:(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *)outer$ {
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "Ljava.util.Map$Entry;", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"Ljava.util.Map$Entry;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalLinkedHashTreeMap_EntrySet", "iterator" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 = { 2, "", "com.google.gson.internal", "LinkedHashTreeMap$EntrySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedHashTreeMap$LinkedTreeMapIterator<Ljava/util/Map$Entry<TK;TV;>;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 *self, ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$->this$0_);
}

ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 *self = [ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1 alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_EntrySet_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_$1)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_KeySet

- (jint)size {
  return this$0_->size_;
}

- (id<JavaUtilIterator>)iterator {
  return [new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(self) autorelease];
}

- (jboolean)containsWithId:(id)o {
  return [this$0_ containsKeyWithId:o];
}

- (jboolean)removeWithId:(id)key {
  return [this$0_ removeInternalByKeyWithId:key] != nil;
}

- (void)clear {
  [this$0_ clear];
}

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$ {
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$);
  return self;
}

- (void)dealloc {
  RELEASE_(this$0_);
  [super dealloc];
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "size", NULL, "I", 0x1, NULL, NULL },
    { "iterator", NULL, "Ljava.util.Iterator;", 0x1, NULL, NULL },
    { "containsWithId:", "contains", "Z", 0x1, NULL, NULL },
    { "removeWithId:", "remove", "Z", 0x1, NULL, NULL },
    { "clear", NULL, "V", 0x1, NULL, NULL },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap:", "init", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.google.gson.internal.LinkedHashTreeMap;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_KeySet = { 2, "KeySet", "com.google.gson.internal", "LinkedHashTreeMap", 0x10, 6, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/util/AbstractSet<TK;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_KeySet;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$) {
  JreStrongAssign(&self->this$0_, outer$);
  JavaUtilAbstractSet_init(self);
}

ComGoogleGsonInternalLinkedHashTreeMap_KeySet *new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet *self = [ComGoogleGsonInternalLinkedHashTreeMap_KeySet alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_KeySet)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1

- (id)next {
  return ((ComGoogleGsonInternalLinkedHashTreeMap_Node *) nil_chk(ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_nextNode(self)))->key_;
}

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet:(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *)outer$ {
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(self, outer$);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "TK;", 0x1, NULL, "()TK;" },
    { "initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet:", "", NULL, 0x0, NULL, NULL },
  };
  static const char *superclass_type_args[] = {"TK;"};
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalLinkedHashTreeMap_KeySet", "iterator" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 = { 2, "", "com.google.gson.internal", "LinkedHashTreeMap$KeySet", 0x8008, 2, methods, 0, NULL, 1, superclass_type_args, 0, NULL, &enclosing_method, "Lcom/google/gson/internal/LinkedHashTreeMap$LinkedTreeMapIterator<TK;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 *self, ComGoogleGsonInternalLinkedHashTreeMap_KeySet *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_LinkedTreeMapIterator_initWithComGoogleGsonInternalLinkedHashTreeMap_(self, outer$->this$0_);
}

ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *outer$) {
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 *self = [ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1 alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1_initWithComGoogleGsonInternalLinkedHashTreeMap_KeySet_(self, outer$);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_KeySet_$1)

@implementation ComGoogleGsonInternalLinkedHashTreeMap_$1

- (jint)compareWithId:(id<JavaLangComparable>)a
               withId:(id<JavaLangComparable>)b {
  return [((id<JavaLangComparable>) nil_chk(a)) compareToWithId:b];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComGoogleGsonInternalLinkedHashTreeMap_$1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "compareWithId:withId:", "compare", "I", 0x1, NULL, NULL },
    { "init", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalLinkedHashTreeMap_$1 = { 2, "", "com.google.gson.internal", "LinkedHashTreeMap", 0x8008, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, "Ljava/lang/Object;Ljava/util/Comparator<Ljava/lang/Comparable;>;" };
  return &_ComGoogleGsonInternalLinkedHashTreeMap_$1;
}

@end

void ComGoogleGsonInternalLinkedHashTreeMap_$1_init(ComGoogleGsonInternalLinkedHashTreeMap_$1 *self) {
  NSObject_init(self);
}

ComGoogleGsonInternalLinkedHashTreeMap_$1 *new_ComGoogleGsonInternalLinkedHashTreeMap_$1_init() {
  ComGoogleGsonInternalLinkedHashTreeMap_$1 *self = [ComGoogleGsonInternalLinkedHashTreeMap_$1 alloc];
  ComGoogleGsonInternalLinkedHashTreeMap_$1_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalLinkedHashTreeMap_$1)
