//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/LinkedHashTreeMap.java
//

#ifndef _LinkedHashTreeMap_H_
#define _LinkedHashTreeMap_H_

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"
#include "java/util/AbstractMap.h"
#include "java/util/AbstractSet.h"
#include "java/util/Map.h"

@class ComGoogleGsonInternalLinkedHashTreeMap_Node;
@class IOSObjectArray;
@protocol JavaUtilComparator;
@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilSet;

@interface ComGoogleGsonInternalLinkedHashTreeMap : JavaUtilAbstractMap < JavaIoSerializable > {
 @public
  id<JavaUtilComparator> comparator_;
  IOSObjectArray *table_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *header_;
  jint size_;
  jint modCount_;
  jint threshold_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

- (void)clear;

- (jboolean)containsKeyWithId:(id)key;

- (id<JavaUtilSet>)entrySet;

- (id)getWithId:(id)key;

- (id<JavaUtilSet>)keySet;

- (id)putWithId:(id)key
         withId:(id)value;

- (id)removeWithId:(id)key;

- (jint)size;

#pragma mark Package-Private

+ (IOSObjectArray *)doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray:(IOSObjectArray *)oldTable;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findWithId:(id)key
                                                withBoolean:(jboolean)create;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findByEntryWithJavaUtilMap_Entry:(id<JavaUtilMap_Entry>)entry_;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)findByObjectWithId:(id)key;

- (void)removeInternalWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node
                                                          withBoolean:(jboolean)unlink;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)removeInternalByKeyWithId:(id)key;

@end

J2OBJC_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap, comparator_, id<JavaUtilComparator>)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap, table_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap, header_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_init(ComGoogleGsonInternalLinkedHashTreeMap *self);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap *new_ComGoogleGsonInternalLinkedHashTreeMap_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(ComGoogleGsonInternalLinkedHashTreeMap *self, id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap *new_ComGoogleGsonInternalLinkedHashTreeMap_initWithJavaUtilComparator_(id<JavaUtilComparator> comparator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IOSObjectArray *ComGoogleGsonInternalLinkedHashTreeMap_doubleCapacityWithComGoogleGsonInternalLinkedHashTreeMap_NodeArray_(IOSObjectArray *oldTable);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap)

@interface ComGoogleGsonInternalLinkedHashTreeMap_Node : NSObject < JavaUtilMap_Entry > {
 @public
  ComGoogleGsonInternalLinkedHashTreeMap_Node *parent_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *left_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *right_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *next_;
  ComGoogleGsonInternalLinkedHashTreeMap_Node *prev_;
  id key_;
  jint hash__;
  id value_;
  jint height_;
}

#pragma mark Public

- (jboolean)isEqual:(id)o;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)first;

- (id)getKey;

- (id)getValue;

- (NSUInteger)hash;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)last;

- (id)setValueWithId:(id)value;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)init;

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)parent
                                                             withId:(id)key
                                                            withInt:(jint)hash_
                    withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)next
                    withComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)prev;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_Node)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, parent_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, left_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, right_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, next_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, prev_, ComGoogleGsonInternalLinkedHashTreeMap_Node *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, key_, id)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalLinkedHashTreeMap_Node, value_, id)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_Node_init(ComGoogleGsonInternalLinkedHashTreeMap_Node *self);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_Node *new_ComGoogleGsonInternalLinkedHashTreeMap_Node_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap_Node *self, ComGoogleGsonInternalLinkedHashTreeMap_Node *parent, id key, jint hash_, ComGoogleGsonInternalLinkedHashTreeMap_Node *next, ComGoogleGsonInternalLinkedHashTreeMap_Node *prev);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_Node *new_ComGoogleGsonInternalLinkedHashTreeMap_Node_initWithComGoogleGsonInternalLinkedHashTreeMap_Node_withId_withInt_withComGoogleGsonInternalLinkedHashTreeMap_Node_withComGoogleGsonInternalLinkedHashTreeMap_Node_(ComGoogleGsonInternalLinkedHashTreeMap_Node *parent, id key, jint hash_, ComGoogleGsonInternalLinkedHashTreeMap_Node *next, ComGoogleGsonInternalLinkedHashTreeMap_Node *prev) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_Node)

@interface ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator : NSObject

#pragma mark Public

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)next;

#pragma mark Package-Private

- (instancetype)init;

- (void)resetWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)root;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *self);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator *new_ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_AvlIterator)

@interface ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder : NSObject

#pragma mark Package-Private

- (instancetype)init;

- (void)addWithComGoogleGsonInternalLinkedHashTreeMap_Node:(ComGoogleGsonInternalLinkedHashTreeMap_Node *)node;

- (void)resetWithInt:(jint)targetSize;

- (ComGoogleGsonInternalLinkedHashTreeMap_Node *)root;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *self);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder *new_ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_AvlBuilder)

@interface ComGoogleGsonInternalLinkedHashTreeMap_EntrySet : JavaUtilAbstractSet

#pragma mark Public

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)o;

- (jint)size;

#pragma mark Package-Private

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_EntrySet *new_ComGoogleGsonInternalLinkedHashTreeMap_EntrySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_EntrySet)

@interface ComGoogleGsonInternalLinkedHashTreeMap_KeySet : JavaUtilAbstractSet

#pragma mark Public

- (void)clear;

- (jboolean)containsWithId:(id)o;

- (id<JavaUtilIterator>)iterator;

- (jboolean)removeWithId:(id)key;

- (jint)size;

#pragma mark Package-Private

- (instancetype)initWithComGoogleGsonInternalLinkedHashTreeMap:(ComGoogleGsonInternalLinkedHashTreeMap *)outer$;


@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalLinkedHashTreeMap_KeySet)

FOUNDATION_EXPORT void ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap_KeySet *self, ComGoogleGsonInternalLinkedHashTreeMap *outer$);

FOUNDATION_EXPORT ComGoogleGsonInternalLinkedHashTreeMap_KeySet *new_ComGoogleGsonInternalLinkedHashTreeMap_KeySet_initWithComGoogleGsonInternalLinkedHashTreeMap_(ComGoogleGsonInternalLinkedHashTreeMap *outer$) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalLinkedHashTreeMap_KeySet)

#endif // _LinkedHashTreeMap_H_
