//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/ObjectConstructor.java
//

#ifndef _ObjectConstructor_H_
#define _ObjectConstructor_H_

#include "J2ObjC_header.h"

@protocol ComGoogleGsonInternalObjectConstructor < NSObject, JavaObject >

- (id)construct;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalObjectConstructor)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalObjectConstructor)

#endif // _ObjectConstructor_H_
