//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/bind/ReflectiveTypeAdapterFactory.java
//

#include "$Gson$Types.h"
#include "ConstructorConstructor.h"
#include "Excluder.h"
#include "FieldNamingStrategy.h"
#include "Gson.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "JsonAdapter.h"
#include "JsonAdapterAnnotationTypeAdapterFactory.h"
#include "JsonReader.h"
#include "JsonSyntaxException.h"
#include "JsonToken.h"
#include "JsonWriter.h"
#include "ObjectConstructor.h"
#include "Primitives.h"
#include "ReflectiveTypeAdapterFactory.h"
#include "SerializedName.h"
#include "TypeAdapter.h"
#include "TypeAdapterRuntimeTypeWrapper.h"
#include "TypeToken.h"
#include "java/io/IOException.h"
#include "java/lang/AssertionError.h"
#include "java/lang/IllegalAccessException.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/reflect/Field.h"
#include "java/lang/reflect/Type.h"
#include "java/util/Collection.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"
#include "java/util/Map.h"

@interface ComGoogleGsonInternalBindReflectiveTypeAdapterFactory () {
 @public
  ComGoogleGsonInternalConstructorConstructor *constructorConstructor_;
  id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy_;
  ComGoogleGsonInternalExcluder *excluder_;
}

- (id<JavaUtilList>)getFieldNamesWithJavaLangReflectField:(JavaLangReflectField *)f;

- (ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *)createBoundFieldWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                                                                                   withJavaLangReflectField:(JavaLangReflectField *)field
                                                                                               withNSString:(NSString *)name
                                                                          withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)fieldType
                                                                                                withBoolean:(jboolean)serialize
                                                                                                withBoolean:(jboolean)deserialize;

- (ComGoogleGsonTypeAdapter *)getFieldAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                                          withJavaLangReflectField:(JavaLangReflectField *)field
                                 withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)fieldType;

- (id<JavaUtilMap>)getBoundFieldsWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                     withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type
                                          withIOSClass:(IOSClass *)raw;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory, constructorConstructor_, ComGoogleGsonInternalConstructorConstructor *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory, fieldNamingPolicy_, id<ComGoogleGsonFieldNamingStrategy>)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory, excluder_, ComGoogleGsonInternalExcluder *)

__attribute__((unused)) static id<JavaUtilList> ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNamesWithJavaLangReflectField_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, JavaLangReflectField *f);

__attribute__((unused)) static ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_createBoundFieldWithComGoogleGsonGson_withJavaLangReflectField_withNSString_withComGoogleGsonReflectTypeToken_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *context, JavaLangReflectField *field, NSString *name, ComGoogleGsonReflectTypeToken *fieldType, jboolean serialize, jboolean deserialize);

__attribute__((unused)) static ComGoogleGsonTypeAdapter *ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldAdapterWithComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *gson, JavaLangReflectField *field, ComGoogleGsonReflectTypeToken *fieldType);

__attribute__((unused)) static id<JavaUtilMap> ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getBoundFieldsWithComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withIOSClass_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *context, ComGoogleGsonReflectTypeToken *type, IOSClass *raw);

@interface ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter () {
 @public
  id<ComGoogleGsonInternalObjectConstructor> constructor_;
  id<JavaUtilMap> boundFields_;
}

- (instancetype)initWithComGoogleGsonInternalObjectConstructor:(id<ComGoogleGsonInternalObjectConstructor>)constructor
                                               withJavaUtilMap:(id<JavaUtilMap>)boundFields;

@end

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter, constructor_, id<ComGoogleGsonInternalObjectConstructor>)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter, boundFields_, id<JavaUtilMap>)

__attribute__((unused)) static void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter *self, id<ComGoogleGsonInternalObjectConstructor> constructor, id<JavaUtilMap> boundFields);

__attribute__((unused)) static ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter *new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(id<ComGoogleGsonInternalObjectConstructor> constructor, id<JavaUtilMap> boundFields) NS_RETURNS_RETAINED;

@interface ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 : ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField {
 @public
  ComGoogleGsonTypeAdapter *typeAdapter_;
  ComGoogleGsonGson *val$context_;
  JavaLangReflectField *val$field_;
  ComGoogleGsonReflectTypeToken *val$fieldType_;
  jboolean val$isPrimitive_;
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer
                                        withId:(id)value;

- (void)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader
                                       withId:(id)value;

- (jboolean)writeFieldWithId:(id)value;

- (instancetype)initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory:(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *)outer$
                                                        withComGoogleGsonGson:(ComGoogleGsonGson *)capture$0
                                                     withJavaLangReflectField:(JavaLangReflectField *)capture$1
                                            withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)capture$2
                                                                  withBoolean:(jboolean)capture$3
                                                                 withNSString:(NSString *)arg$0
                                                                  withBoolean:(jboolean)arg$1
                                                                  withBoolean:(jboolean)arg$2;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1)

J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1, typeAdapter_, ComGoogleGsonTypeAdapter *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1, val$context_, ComGoogleGsonGson *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1, val$field_, JavaLangReflectField *)
J2OBJC_FIELD_SETTER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1, val$fieldType_, ComGoogleGsonReflectTypeToken *)

__attribute__((unused)) static void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 *self, ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *outer$, ComGoogleGsonGson *capture$0, JavaLangReflectField *capture$1, ComGoogleGsonReflectTypeToken *capture$2, jboolean capture$3, NSString *arg$0, jboolean arg$1, jboolean arg$2);

__attribute__((unused)) static ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 *new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *outer$, ComGoogleGsonGson *capture$0, JavaLangReflectField *capture$1, ComGoogleGsonReflectTypeToken *capture$2, jboolean capture$3, NSString *arg$0, jboolean arg$1, jboolean arg$2) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1)

@implementation ComGoogleGsonInternalBindReflectiveTypeAdapterFactory

- (instancetype)initWithComGoogleGsonInternalConstructorConstructor:(ComGoogleGsonInternalConstructorConstructor *)constructorConstructor
                               withComGoogleGsonFieldNamingStrategy:(id<ComGoogleGsonFieldNamingStrategy>)fieldNamingPolicy
                                  withComGoogleGsonInternalExcluder:(ComGoogleGsonInternalExcluder *)excluder {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonFieldNamingStrategy_withComGoogleGsonInternalExcluder_(self, constructorConstructor, fieldNamingPolicy, excluder);
  return self;
}

- (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)f
                                     withBoolean:(jboolean)serialize {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withComGoogleGsonInternalExcluder_(f, serialize, excluder_);
}

+ (jboolean)excludeFieldWithJavaLangReflectField:(JavaLangReflectField *)f
                                     withBoolean:(jboolean)serialize
               withComGoogleGsonInternalExcluder:(ComGoogleGsonInternalExcluder *)excluder {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withComGoogleGsonInternalExcluder_(f, serialize, excluder);
}

- (id<JavaUtilList>)getFieldNamesWithJavaLangReflectField:(JavaLangReflectField *)f {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNamesWithJavaLangReflectField_(self, f);
}

+ (id<JavaUtilList>)getFieldNameWithComGoogleGsonFieldNamingStrategy:(id<ComGoogleGsonFieldNamingStrategy>)fieldNamingPolicy
                                            withJavaLangReflectField:(JavaLangReflectField *)f {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNameWithComGoogleGsonFieldNamingStrategy_withJavaLangReflectField_(fieldNamingPolicy, f);
}

- (ComGoogleGsonTypeAdapter *)createWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                        withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type {
  IOSClass *raw = [((ComGoogleGsonReflectTypeToken *) nil_chk(type)) getRawType];
  if (![NSObject_class_() isAssignableFrom:raw]) {
    return nil;
  }
  id<ComGoogleGsonInternalObjectConstructor> constructor = [((ComGoogleGsonInternalConstructorConstructor *) nil_chk(constructorConstructor_)) getWithComGoogleGsonReflectTypeToken:type];
  return [new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(constructor, ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getBoundFieldsWithComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withIOSClass_(self, gson, type, raw)) autorelease];
}

- (ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *)createBoundFieldWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                                                                                   withJavaLangReflectField:(JavaLangReflectField *)field
                                                                                               withNSString:(NSString *)name
                                                                          withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)fieldType
                                                                                                withBoolean:(jboolean)serialize
                                                                                                withBoolean:(jboolean)deserialize {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_createBoundFieldWithComGoogleGsonGson_withJavaLangReflectField_withNSString_withComGoogleGsonReflectTypeToken_withBoolean_withBoolean_(self, context, field, name, fieldType, serialize, deserialize);
}

- (ComGoogleGsonTypeAdapter *)getFieldAdapterWithComGoogleGsonGson:(ComGoogleGsonGson *)gson
                                          withJavaLangReflectField:(JavaLangReflectField *)field
                                 withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)fieldType {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldAdapterWithComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_(self, gson, field, fieldType);
}

- (id<JavaUtilMap>)getBoundFieldsWithComGoogleGsonGson:(ComGoogleGsonGson *)context
                     withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)type
                                          withIOSClass:(IOSClass *)raw {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getBoundFieldsWithComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withIOSClass_(self, context, type, raw);
}

- (void)dealloc {
  RELEASE_(constructorConstructor_);
  RELEASE_(fieldNamingPolicy_);
  RELEASE_(excluder_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComGoogleGsonInternalConstructorConstructor:withComGoogleGsonFieldNamingStrategy:withComGoogleGsonInternalExcluder:", "ReflectiveTypeAdapterFactory", NULL, 0x1, NULL, NULL },
    { "excludeFieldWithJavaLangReflectField:withBoolean:", "excludeField", "Z", 0x1, NULL, NULL },
    { "excludeFieldWithJavaLangReflectField:withBoolean:withComGoogleGsonInternalExcluder:", "excludeField", "Z", 0x8, NULL, NULL },
    { "getFieldNamesWithJavaLangReflectField:", "getFieldNames", "Ljava.util.List;", 0x2, NULL, NULL },
    { "getFieldNameWithComGoogleGsonFieldNamingStrategy:withJavaLangReflectField:", "getFieldName", "Ljava.util.List;", 0x8, NULL, NULL },
    { "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x1, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
    { "createBoundFieldWithComGoogleGsonGson:withJavaLangReflectField:withNSString:withComGoogleGsonReflectTypeToken:withBoolean:withBoolean:", "createBoundField", "Lcom.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField;", 0x2, NULL, NULL },
    { "getFieldAdapterWithComGoogleGsonGson:withJavaLangReflectField:withComGoogleGsonReflectTypeToken:", "getFieldAdapter", "Lcom.google.gson.TypeAdapter;", 0x2, NULL, NULL },
    { "getBoundFieldsWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:withIOSClass:", "getBoundFields", "Ljava.util.Map;", 0x2, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "constructorConstructor_", NULL, 0x12, "Lcom.google.gson.internal.ConstructorConstructor;", NULL, NULL, .constantValue.asLong = 0 },
    { "fieldNamingPolicy_", NULL, 0x12, "Lcom.google.gson.FieldNamingStrategy;", NULL, NULL, .constantValue.asLong = 0 },
    { "excluder_", NULL, 0x12, "Lcom.google.gson.internal.Excluder;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Lcom.google.gson.internal.bind.ReflectiveTypeAdapterFactory$BoundField;", "Lcom.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindReflectiveTypeAdapterFactory = { 2, "ReflectiveTypeAdapterFactory", "com.google.gson.internal.bind", NULL, 0x11, 9, methods, 3, fields, 0, NULL, 2, inner_classes, NULL, NULL };
  return &_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory;
}

@end

void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonFieldNamingStrategy_withComGoogleGsonInternalExcluder_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonInternalConstructorConstructor *constructorConstructor, id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy, ComGoogleGsonInternalExcluder *excluder) {
  NSObject_init(self);
  JreStrongAssign(&self->constructorConstructor_, constructorConstructor);
  JreStrongAssign(&self->fieldNamingPolicy_, fieldNamingPolicy);
  JreStrongAssign(&self->excluder_, excluder);
}

ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonFieldNamingStrategy_withComGoogleGsonInternalExcluder_(ComGoogleGsonInternalConstructorConstructor *constructorConstructor, id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy, ComGoogleGsonInternalExcluder *excluder) {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self = [ComGoogleGsonInternalBindReflectiveTypeAdapterFactory alloc];
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonFieldNamingStrategy_withComGoogleGsonInternalExcluder_(self, constructorConstructor, fieldNamingPolicy, excluder);
  return self;
}

jboolean ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_excludeFieldWithJavaLangReflectField_withBoolean_withComGoogleGsonInternalExcluder_(JavaLangReflectField *f, jboolean serialize, ComGoogleGsonInternalExcluder *excluder) {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initialize();
  return ![((ComGoogleGsonInternalExcluder *) nil_chk(excluder)) excludeClassWithIOSClass:[((JavaLangReflectField *) nil_chk(f)) getType] withBoolean:serialize] && ![excluder excludeFieldWithJavaLangReflectField:f withBoolean:serialize];
}

id<JavaUtilList> ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNamesWithJavaLangReflectField_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, JavaLangReflectField *f) {
  return ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNameWithComGoogleGsonFieldNamingStrategy_withJavaLangReflectField_(self->fieldNamingPolicy_, f);
}

id<JavaUtilList> ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNameWithComGoogleGsonFieldNamingStrategy_withJavaLangReflectField_(id<ComGoogleGsonFieldNamingStrategy> fieldNamingPolicy, JavaLangReflectField *f) {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_initialize();
  id<ComGoogleGsonAnnotationsSerializedName> serializedName = [((JavaLangReflectField *) nil_chk(f)) getAnnotationWithIOSClass:ComGoogleGsonAnnotationsSerializedName_class_()];
  id<JavaUtilList> fieldNames = [new_JavaUtilLinkedList_init() autorelease];
  if (serializedName == nil) {
    [fieldNames addWithId:[((id<ComGoogleGsonFieldNamingStrategy>) nil_chk(fieldNamingPolicy)) translateNameWithJavaLangReflectField:f]];
  }
  else {
    [fieldNames addWithId:[serializedName value]];
    {
      IOSObjectArray *a__ = [serializedName alternate];
      NSString * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
      NSString * const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        NSString *alternate = *b__++;
        [fieldNames addWithId:alternate];
      }
    }
  }
  return fieldNames;
}

ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_createBoundFieldWithComGoogleGsonGson_withJavaLangReflectField_withNSString_withComGoogleGsonReflectTypeToken_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *context, JavaLangReflectField *field, NSString *name, ComGoogleGsonReflectTypeToken *fieldType, jboolean serialize, jboolean deserialize) {
  jboolean isPrimitive = ComGoogleGsonInternalPrimitives_isPrimitiveWithJavaLangReflectType_([((ComGoogleGsonReflectTypeToken *) nil_chk(fieldType)) getRawType]);
  return [new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(self, context, field, fieldType, isPrimitive, name, serialize, deserialize) autorelease];
}

ComGoogleGsonTypeAdapter *ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldAdapterWithComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *gson, JavaLangReflectField *field, ComGoogleGsonReflectTypeToken *fieldType) {
  id<ComGoogleGsonAnnotationsJsonAdapter> annotation = [((JavaLangReflectField *) nil_chk(field)) getAnnotationWithIOSClass:ComGoogleGsonAnnotationsJsonAdapter_class_()];
  if (annotation != nil) {
    ComGoogleGsonTypeAdapter *adapter = ComGoogleGsonInternalBindJsonAdapterAnnotationTypeAdapterFactory_getTypeAdapterWithComGoogleGsonInternalConstructorConstructor_withComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withComGoogleGsonAnnotationsJsonAdapter_(self->constructorConstructor_, gson, fieldType, annotation);
    if (adapter != nil) return adapter;
  }
  return [((ComGoogleGsonGson *) nil_chk(gson)) getAdapterWithComGoogleGsonReflectTypeToken:fieldType];
}

id<JavaUtilMap> ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getBoundFieldsWithComGoogleGsonGson_withComGoogleGsonReflectTypeToken_withIOSClass_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *self, ComGoogleGsonGson *context, ComGoogleGsonReflectTypeToken *type, IOSClass *raw) {
  id<JavaUtilMap> result = [new_JavaUtilLinkedHashMap_init() autorelease];
  if ([((IOSClass *) nil_chk(raw)) isInterface]) {
    return result;
  }
  id<JavaLangReflectType> declaredType = [((ComGoogleGsonReflectTypeToken *) nil_chk(type)) getType];
  while (raw != NSObject_class_()) {
    IOSObjectArray *fields = [raw getDeclaredFields];
    {
      IOSObjectArray *a__ = fields;
      JavaLangReflectField * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
      JavaLangReflectField * const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        JavaLangReflectField *field = *b__++;
        jboolean serialize = [self excludeFieldWithJavaLangReflectField:field withBoolean:true];
        jboolean deserialize = [self excludeFieldWithJavaLangReflectField:field withBoolean:false];
        if (!serialize && !deserialize) {
          continue;
        }
        [((JavaLangReflectField *) nil_chk(field)) setAccessibleWithBoolean:true];
        id<JavaLangReflectType> fieldType = ComGoogleGsonInternal$Gson$Types_resolveWithJavaLangReflectType_withIOSClass_withJavaLangReflectType_([type getType], raw, [field getGenericType]);
        id<JavaUtilList> fieldNames = ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldNamesWithJavaLangReflectField_(self, field);
        ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *previous = nil;
        for (jint i = 0; i < [((id<JavaUtilList>) nil_chk(fieldNames)) size]; ++i) {
          NSString *name = [fieldNames getWithInt:i];
          if (i != 0) serialize = false;
          ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *boundField = ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_createBoundFieldWithComGoogleGsonGson_withJavaLangReflectField_withNSString_withComGoogleGsonReflectTypeToken_withBoolean_withBoolean_(self, context, field, name, ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(fieldType), serialize, deserialize);
          ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *replaced = [result putWithId:name withId:boundField];
          if (previous == nil) previous = replaced;
        }
        if (previous != nil) {
          @throw [new_JavaLangIllegalArgumentException_initWithNSString_(JreStrcat("@$$", declaredType, @" declares multiple JSON fields named ", previous->name_)) autorelease];
        }
      }
    }
    type = ComGoogleGsonReflectTypeToken_getWithJavaLangReflectType_(ComGoogleGsonInternal$Gson$Types_resolveWithJavaLangReflectType_withIOSClass_withJavaLangReflectType_([type getType], raw, [raw getGenericSuperclass]));
    raw = [((ComGoogleGsonReflectTypeToken *) nil_chk(type)) getRawType];
  }
  return result;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory)

@implementation ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField

- (instancetype)initWithNSString:(NSString *)name
                     withBoolean:(jboolean)serialized
                     withBoolean:(jboolean)deserialized {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(self, name, serialized, deserialized);
  return self;
}

- (jboolean)writeFieldWithId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer
                                        withId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader
                                       withId:(id)value {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
}

- (void)dealloc {
  RELEASE_(name_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withBoolean:withBoolean:", "BoundField", NULL, 0x4, NULL, NULL },
    { "writeFieldWithId:", "writeField", "Z", 0x400, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x400, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
    { "readWithComGoogleGsonStreamJsonReader:withId:", "read", "V", 0x400, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "name_", NULL, 0x10, "Ljava.lang.String;", NULL, NULL, .constantValue.asLong = 0 },
    { "serialized_", NULL, 0x10, "Z", NULL, NULL, .constantValue.asLong = 0 },
    { "deserialized_", NULL, 0x10, "Z", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField = { 2, "BoundField", "com.google.gson.internal.bind", "ReflectiveTypeAdapterFactory", 0x408, 4, methods, 3, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField;
}

@end

void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *self, NSString *name, jboolean serialized, jboolean deserialized) {
  NSObject_init(self);
  JreStrongAssign(&self->name_, name);
  self->serialized_ = serialized;
  self->deserialized_ = deserialized;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField)

@implementation ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter

- (instancetype)initWithComGoogleGsonInternalObjectConstructor:(id<ComGoogleGsonInternalObjectConstructor>)constructor
                                               withJavaUtilMap:(id<JavaUtilMap>)boundFields {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(self, constructor, boundFields);
  return self;
}

- (id)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)inArg {
  if ([((ComGoogleGsonStreamJsonReader *) nil_chk(inArg)) peek] == JreLoadStatic(ComGoogleGsonStreamJsonTokenEnum, NULL)) {
    [inArg nextNull];
    return nil;
  }
  id instance = [((id<ComGoogleGsonInternalObjectConstructor>) nil_chk(constructor_)) construct];
  @try {
    [inArg beginObject];
    while ([inArg hasNext]) {
      NSString *name = [inArg nextName];
      ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *field = [((id<JavaUtilMap>) nil_chk(boundFields_)) getWithId:name];
      if (field == nil || !field->deserialized_) {
        [inArg skipValue];
      }
      else {
        [field readWithComGoogleGsonStreamJsonReader:inArg withId:instance];
      }
    }
  }
  @catch (JavaLangIllegalStateException *e) {
    @throw [new_ComGoogleGsonJsonSyntaxException_initWithJavaLangThrowable_(e) autorelease];
  }
  @catch (JavaLangIllegalAccessException *e) {
    @throw [new_JavaLangAssertionError_initWithId_(e) autorelease];
  }
  [inArg endObject];
  return instance;
}

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)outArg
                                        withId:(id)value {
  if (value == nil) {
    [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) nullValue];
    return;
  }
  [((ComGoogleGsonStreamJsonWriter *) nil_chk(outArg)) beginObject];
  @try {
    for (ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField * __strong boundField in nil_chk([((id<JavaUtilMap>) nil_chk(boundFields_)) values])) {
      if ([((ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField *) nil_chk(boundField)) writeFieldWithId:value]) {
        [outArg nameWithNSString:boundField->name_];
        [boundField writeWithComGoogleGsonStreamJsonWriter:outArg withId:value];
      }
    }
  }
  @catch (JavaLangIllegalAccessException *e) {
    @throw [new_JavaLangAssertionError_init() autorelease];
  }
  [outArg endObject];
}

- (void)dealloc {
  RELEASE_(constructor_);
  RELEASE_(boundFields_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithComGoogleGsonInternalObjectConstructor:withJavaUtilMap:", "Adapter", NULL, 0x2, NULL, NULL },
    { "readWithComGoogleGsonStreamJsonReader:", "read", "TT;", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonReader;)TT;" },
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x1, "Ljava.io.IOException;", "(Lcom/google/gson/stream/JsonWriter;TT;)V" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "constructor_", NULL, 0x12, "Lcom.google.gson.internal.ObjectConstructor;", NULL, "Lcom/google/gson/internal/ObjectConstructor<TT;>;", .constantValue.asLong = 0 },
    { "boundFields_", NULL, 0x12, "Ljava.util.Map;", NULL, "Ljava/util/Map<Ljava/lang/String;Lcom/google/gson/internal/bind/ReflectiveTypeAdapterFactory$BoundField;>;", .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"TT;"};
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter = { 2, "Adapter", "com.google.gson.internal.bind", "ReflectiveTypeAdapterFactory", 0x19, 3, methods, 2, fields, 1, superclass_type_args, 0, NULL, NULL, "<T:Ljava/lang/Object;>Lcom/google/gson/TypeAdapter<TT;>;" };
  return &_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter;
}

@end

void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter *self, id<ComGoogleGsonInternalObjectConstructor> constructor, id<JavaUtilMap> boundFields) {
  ComGoogleGsonTypeAdapter_init(self);
  JreStrongAssign(&self->constructor_, constructor);
  JreStrongAssign(&self->boundFields_, boundFields);
}

ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter *new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(id<ComGoogleGsonInternalObjectConstructor> constructor, id<JavaUtilMap> boundFields) {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter *self = [ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter alloc];
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter_initWithComGoogleGsonInternalObjectConstructor_withJavaUtilMap_(self, constructor, boundFields);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_Adapter)

@implementation ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1

- (void)writeWithComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer
                                        withId:(id)value {
  id fieldValue = [((JavaLangReflectField *) nil_chk(val$field_)) getWithId:value];
  ComGoogleGsonTypeAdapter *t = [new_ComGoogleGsonInternalBindTypeAdapterRuntimeTypeWrapper_initWithComGoogleGsonGson_withComGoogleGsonTypeAdapter_withJavaLangReflectType_(val$context_, self->typeAdapter_, [((ComGoogleGsonReflectTypeToken *) nil_chk(val$fieldType_)) getType]) autorelease];
  [t writeWithComGoogleGsonStreamJsonWriter:writer withId:fieldValue];
}

- (void)readWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader
                                       withId:(id)value {
  id fieldValue = [((ComGoogleGsonTypeAdapter *) nil_chk(typeAdapter_)) readWithComGoogleGsonStreamJsonReader:reader];
  if (fieldValue != nil || !val$isPrimitive_) {
    [((JavaLangReflectField *) nil_chk(val$field_)) setWithId:value withId:fieldValue];
  }
}

- (jboolean)writeFieldWithId:(id)value {
  if (!serialized_) return false;
  id fieldValue = [((JavaLangReflectField *) nil_chk(val$field_)) getWithId:value];
  return fieldValue != value;
}

- (instancetype)initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory:(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *)outer$
                                                        withComGoogleGsonGson:(ComGoogleGsonGson *)capture$0
                                                     withJavaLangReflectField:(JavaLangReflectField *)capture$1
                                            withComGoogleGsonReflectTypeToken:(ComGoogleGsonReflectTypeToken *)capture$2
                                                                  withBoolean:(jboolean)capture$3
                                                                 withNSString:(NSString *)arg$0
                                                                  withBoolean:(jboolean)arg$1
                                                                  withBoolean:(jboolean)arg$2 {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(self, outer$, capture$0, capture$1, capture$2, capture$3, arg$0, arg$1, arg$2);
  return self;
}

- (void)dealloc {
  RELEASE_(typeAdapter_);
  RELEASE_(val$context_);
  RELEASE_(val$field_);
  RELEASE_(val$fieldType_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "writeWithComGoogleGsonStreamJsonWriter:withId:", "write", "V", 0x0, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
    { "readWithComGoogleGsonStreamJsonReader:withId:", "read", "V", 0x0, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
    { "writeFieldWithId:", "writeField", "Z", 0x1, "Ljava.io.IOException;Ljava.lang.IllegalAccessException;", NULL },
    { "initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory:withComGoogleGsonGson:withJavaLangReflectField:withComGoogleGsonReflectTypeToken:withBoolean:withNSString:withBoolean:withBoolean:", "", NULL, 0x0, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "typeAdapter_", NULL, 0x10, "Lcom.google.gson.TypeAdapter;", NULL, "Lcom/google/gson/TypeAdapter<*>;", .constantValue.asLong = 0 },
    { "val$context_", NULL, 0x1012, "Lcom.google.gson.Gson;", NULL, NULL, .constantValue.asLong = 0 },
    { "val$field_", NULL, 0x1012, "Ljava.lang.reflect.Field;", NULL, NULL, .constantValue.asLong = 0 },
    { "val$fieldType_", NULL, 0x1012, "Lcom.google.gson.reflect.TypeToken;", NULL, "Lcom/google/gson/reflect/TypeToken<*>;", .constantValue.asLong = 0 },
    { "val$isPrimitive_", NULL, 0x1012, "Z", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjCEnclosingMethodInfo enclosing_method = { "ComGoogleGsonInternalBindReflectiveTypeAdapterFactory", "createBoundFieldWithComGoogleGsonGson:withJavaLangReflectField:withNSString:withComGoogleGsonReflectTypeToken:withBoolean:withBoolean:" };
  static const J2ObjcClassInfo _ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 = { 2, "", "com.google.gson.internal.bind", "ReflectiveTypeAdapterFactory", 0x8008, 4, methods, 5, fields, 0, NULL, 0, NULL, &enclosing_method, NULL };
  return &_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1;
}

@end

void ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 *self, ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *outer$, ComGoogleGsonGson *capture$0, JavaLangReflectField *capture$1, ComGoogleGsonReflectTypeToken *capture$2, jboolean capture$3, NSString *arg$0, jboolean arg$1, jboolean arg$2) {
  JreStrongAssign(&self->val$context_, capture$0);
  JreStrongAssign(&self->val$field_, capture$1);
  JreStrongAssign(&self->val$fieldType_, capture$2);
  self->val$isPrimitive_ = capture$3;
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_BoundField_initWithNSString_withBoolean_withBoolean_(self, arg$0, arg$1, arg$2);
  JreStrongAssign(&self->typeAdapter_, ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_getFieldAdapterWithComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_(outer$, self->val$context_, self->val$field_, self->val$fieldType_));
}

ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 *new_ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory *outer$, ComGoogleGsonGson *capture$0, JavaLangReflectField *capture$1, ComGoogleGsonReflectTypeToken *capture$2, jboolean capture$3, NSString *arg$0, jboolean arg$1, jboolean arg$2) {
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 *self = [ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1 alloc];
  ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1_initWithComGoogleGsonInternalBindReflectiveTypeAdapterFactory_withComGoogleGsonGson_withJavaLangReflectField_withComGoogleGsonReflectTypeToken_withBoolean_withNSString_withBoolean_withBoolean_(self, outer$, capture$0, capture$1, capture$2, capture$3, arg$0, arg$1, arg$2);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGoogleGsonInternalBindReflectiveTypeAdapterFactory_$1)
