//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/annotations/SerializedName.java
//

#ifndef _SerializedName_H_
#define _SerializedName_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

@protocol ComGoogleGsonAnnotationsSerializedName < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;
@property (readonly) IOSObjectArray *alternate;

@end

@interface ComGoogleGsonAnnotationsSerializedName : NSObject < ComGoogleGsonAnnotationsSerializedName > {
 @private
  NSString *value_;
  IOSObjectArray *alternate_;
}

- (instancetype)initWithAlternate:(IOSObjectArray *)alternate__ withValue:(NSString *)value__;

+ (IOSObjectArray *)alternateDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonAnnotationsSerializedName)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonAnnotationsSerializedName)

#endif // _SerializedName_H_
