//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/Streams.java
//

#ifndef _Streams_H_
#define _Streams_H_

#include "J2ObjC_header.h"

@class ComGoogleGsonJsonElement;
@class ComGoogleGsonStreamJsonReader;
@class ComGoogleGsonStreamJsonWriter;
@class JavaIoWriter;
@protocol JavaLangAppendable;

@interface ComGoogleGsonInternalStreams : NSObject

#pragma mark Public

+ (ComGoogleGsonJsonElement *)parseWithComGoogleGsonStreamJsonReader:(ComGoogleGsonStreamJsonReader *)reader;

+ (void)writeWithComGoogleGsonJsonElement:(ComGoogleGsonJsonElement *)element
        withComGoogleGsonStreamJsonWriter:(ComGoogleGsonStreamJsonWriter *)writer;

+ (JavaIoWriter *)writerForAppendableWithJavaLangAppendable:(id<JavaLangAppendable>)appendable;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalStreams)

FOUNDATION_EXPORT ComGoogleGsonJsonElement *ComGoogleGsonInternalStreams_parseWithComGoogleGsonStreamJsonReader_(ComGoogleGsonStreamJsonReader *reader);

FOUNDATION_EXPORT void ComGoogleGsonInternalStreams_writeWithComGoogleGsonJsonElement_withComGoogleGsonStreamJsonWriter_(ComGoogleGsonJsonElement *element, ComGoogleGsonStreamJsonWriter *writer);

FOUNDATION_EXPORT JavaIoWriter *ComGoogleGsonInternalStreams_writerForAppendableWithJavaLangAppendable_(id<JavaLangAppendable> appendable);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalStreams)

#endif // _Streams_H_
