//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/TypeAdapterFactory.java
//

#include "Gson.h"
#include "J2ObjC_source.h"
#include "TypeAdapter.h"
#include "TypeAdapterFactory.h"
#include "TypeToken.h"

@interface ComGoogleGsonTypeAdapterFactory : NSObject

@end

@implementation ComGoogleGsonTypeAdapterFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createWithComGoogleGsonGson:withComGoogleGsonReflectTypeToken:", "create", "Lcom.google.gson.TypeAdapter;", 0x401, NULL, "<T:Ljava/lang/Object;>(Lcom/google/gson/Gson;Lcom/google/gson/reflect/TypeToken<TT;>;)Lcom/google/gson/TypeAdapter<TT;>;" },
  };
  static const J2ObjcClassInfo _ComGoogleGsonTypeAdapterFactory = { 2, "TypeAdapterFactory", "com.google.gson", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComGoogleGsonTypeAdapterFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGoogleGsonTypeAdapterFactory)
