//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//com/google/gson/internal/UnsafeAllocator.java
//

#ifndef _UnsafeAllocator_H_
#define _UnsafeAllocator_H_

#include "J2ObjC_header.h"

@class IOSClass;

@interface ComGoogleGsonInternalUnsafeAllocator : NSObject

#pragma mark Public

- (instancetype)init;

+ (ComGoogleGsonInternalUnsafeAllocator *)create;

- (id)newInstanceWithIOSClass:(IOSClass *)c OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleGsonInternalUnsafeAllocator)

FOUNDATION_EXPORT ComGoogleGsonInternalUnsafeAllocator *ComGoogleGsonInternalUnsafeAllocator_create();

FOUNDATION_EXPORT void ComGoogleGsonInternalUnsafeAllocator_init(ComGoogleGsonInternalUnsafeAllocator *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleGsonInternalUnsafeAllocator)

#endif // _UnsafeAllocator_H_
