//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/Collections.java
//

#ifndef _Collections_H_
#define _Collections_H_

#include "J2ObjC_header.h"

@class JavaUtilLinkedHashMap;
@class JavaUtilLinkedHashSet;

@interface DaggerInternalCollections : NSObject

#pragma mark Package-Private

+ (JavaUtilLinkedHashMap *)newLinkedHashMapWithExpectedSizeWithInt:(jint)expectedSize OBJC_METHOD_FAMILY_NONE;

+ (JavaUtilLinkedHashSet *)newLinkedHashSetWithExpectedSizeWithInt:(jint)expectedSize OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalCollections)

FOUNDATION_EXPORT JavaUtilLinkedHashSet *DaggerInternalCollections_newLinkedHashSetWithExpectedSizeWithInt_(jint expectedSize);

FOUNDATION_EXPORT JavaUtilLinkedHashMap *DaggerInternalCollections_newLinkedHashMapWithExpectedSizeWithInt_(jint expectedSize);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalCollections)

#endif // _Collections_H_
