//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Component.java
//

#ifndef _Component_H_
#define _Component_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

@protocol DaggerComponent < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *modules;
@property (readonly) IOSObjectArray *dependencies;

@end

@interface DaggerComponent : NSObject < DaggerComponent > {
 @private
  IOSObjectArray *modules_;
  IOSObjectArray *dependencies_;
}

- (instancetype)initWithDependencies:(IOSObjectArray *)dependencies__ withModules:(IOSObjectArray *)modules__;

+ (IOSObjectArray *)modulesDefault;
+ (IOSObjectArray *)dependenciesDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerComponent)

J2OBJC_TYPE_LITERAL_HEADER(DaggerComponent)

@protocol DaggerComponent_Builder < JavaLangAnnotationAnnotation >

@end

@interface DaggerComponent_Builder : NSObject < DaggerComponent_Builder >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerComponent_Builder)

J2OBJC_TYPE_LITERAL_HEADER(DaggerComponent_Builder)

#endif // _Component_H_
