//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/DoubleCheckLazy.java
//

#ifndef _DoubleCheckLazy_H_
#define _DoubleCheckLazy_H_

#include "J2ObjC_header.h"
#include "Lazy.h"

@protocol JavaxInjectProvider;

@interface DaggerInternalDoubleCheckLazy : NSObject < DaggerLazy >

#pragma mark Public

+ (id<DaggerLazy>)createWithJavaxInjectProvider:(id<JavaxInjectProvider>)provider;

- (id)get;

@end

J2OBJC_STATIC_INIT(DaggerInternalDoubleCheckLazy)

FOUNDATION_EXPORT id<DaggerLazy> DaggerInternalDoubleCheckLazy_createWithJavaxInjectProvider_(id<JavaxInjectProvider> provider);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalDoubleCheckLazy)

#endif // _DoubleCheckLazy_H_
