//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/Factory.java
//

#ifndef _Factory_H_
#define _Factory_H_

#include "J2ObjC_header.h"
#include "javax/inject/Provider.h"

@protocol DaggerInternalFactory < JavaxInjectProvider, NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalFactory)

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalFactory)

#endif // _Factory_H_
