//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/MapProviderFactory.java
//

#include "Collections.h"
#include "J2ObjC_source.h"
#include "MapProviderFactory.h"
#include "java/lang/NullPointerException.h"
#include "java/util/Collections.h"
#include "java/util/LinkedHashMap.h"
#include "java/util/Map.h"
#include "javax/inject/Provider.h"

@interface DaggerInternalMapProviderFactory () {
 @public
  id<JavaUtilMap> contributingMap_;
}

- (instancetype)initWithJavaUtilLinkedHashMap:(JavaUtilLinkedHashMap *)contributingMap;

@end

J2OBJC_FIELD_SETTER(DaggerInternalMapProviderFactory, contributingMap_, id<JavaUtilMap>)

__attribute__((unused)) static void DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(DaggerInternalMapProviderFactory *self, JavaUtilLinkedHashMap *contributingMap);

__attribute__((unused)) static DaggerInternalMapProviderFactory *new_DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(JavaUtilLinkedHashMap *contributingMap) NS_RETURNS_RETAINED;

@interface DaggerInternalMapProviderFactory_Builder () {
 @public
  JavaUtilLinkedHashMap *mapBuilder_;
}

- (instancetype)initWithInt:(jint)size;

@end

J2OBJC_FIELD_SETTER(DaggerInternalMapProviderFactory_Builder, mapBuilder_, JavaUtilLinkedHashMap *)

__attribute__((unused)) static void DaggerInternalMapProviderFactory_Builder_initWithInt_(DaggerInternalMapProviderFactory_Builder *self, jint size);

__attribute__((unused)) static DaggerInternalMapProviderFactory_Builder *new_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size) NS_RETURNS_RETAINED;

@implementation DaggerInternalMapProviderFactory

+ (DaggerInternalMapProviderFactory_Builder *)builderWithInt:(jint)size {
  return DaggerInternalMapProviderFactory_builderWithInt_(size);
}

- (instancetype)initWithJavaUtilLinkedHashMap:(JavaUtilLinkedHashMap *)contributingMap {
  DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(self, contributingMap);
  return self;
}

- (id<JavaUtilMap>)get {
  return self->contributingMap_;
}

- (void)dealloc {
  RELEASE_(contributingMap_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "builderWithInt:", "builder", "Ldagger.internal.MapProviderFactory$Builder;", 0x9, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>(I)Ldagger/internal/MapProviderFactory$Builder<TK;TV;>;" },
    { "initWithJavaUtilLinkedHashMap:", "MapProviderFactory", NULL, 0x2, NULL, NULL },
    { "get", NULL, "Ljava.util.Map;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "contributingMap_", NULL, 0x12, "Ljava.util.Map;", NULL, "Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;", .constantValue.asLong = 0 },
  };
  static const char *inner_classes[] = {"Ldagger.internal.MapProviderFactory$Builder;"};
  static const J2ObjcClassInfo _DaggerInternalMapProviderFactory = { 2, "MapProviderFactory", "dagger.internal", NULL, 0x11, 3, methods, 1, fields, 0, NULL, 1, inner_classes, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;Ldagger/internal/Factory<Ljava/util/Map<TK;Ljavax/inject/Provider<TV;>;>;>;" };
  return &_DaggerInternalMapProviderFactory;
}

@end

DaggerInternalMapProviderFactory_Builder *DaggerInternalMapProviderFactory_builderWithInt_(jint size) {
  DaggerInternalMapProviderFactory_initialize();
  return [new_DaggerInternalMapProviderFactory_Builder_initWithInt_(size) autorelease];
}

void DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(DaggerInternalMapProviderFactory *self, JavaUtilLinkedHashMap *contributingMap) {
  NSObject_init(self);
  JreStrongAssign(&self->contributingMap_, JavaUtilCollections_unmodifiableMapWithJavaUtilMap_(contributingMap));
}

DaggerInternalMapProviderFactory *new_DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(JavaUtilLinkedHashMap *contributingMap) {
  DaggerInternalMapProviderFactory *self = [DaggerInternalMapProviderFactory alloc];
  DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(self, contributingMap);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMapProviderFactory)

@implementation DaggerInternalMapProviderFactory_Builder

- (instancetype)initWithInt:(jint)size {
  DaggerInternalMapProviderFactory_Builder_initWithInt_(self, size);
  return self;
}

- (DaggerInternalMapProviderFactory *)build {
  return [new_DaggerInternalMapProviderFactory_initWithJavaUtilLinkedHashMap_(self->mapBuilder_) autorelease];
}

- (DaggerInternalMapProviderFactory_Builder *)putWithId:(id)key
                                withJavaxInjectProvider:(id<JavaxInjectProvider>)providerOfValue {
  if (key == nil) {
    @throw [new_JavaLangNullPointerException_initWithNSString_(@"The key is null") autorelease];
  }
  if (providerOfValue == nil) {
    @throw [new_JavaLangNullPointerException_initWithNSString_(@"The provider of the value is null") autorelease];
  }
  [((JavaUtilLinkedHashMap *) nil_chk(self->mapBuilder_)) putWithId:key withId:providerOfValue];
  return self;
}

- (void)dealloc {
  RELEASE_(mapBuilder_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:", "Builder", NULL, 0x2, NULL, NULL },
    { "build", NULL, "Ldagger.internal.MapProviderFactory;", 0x1, NULL, NULL },
    { "putWithId:withJavaxInjectProvider:", "put", "Ldagger.internal.MapProviderFactory$Builder;", 0x1, NULL, "(TK;Ljavax/inject/Provider<TV;>;)Ldagger/internal/MapProviderFactory$Builder<TK;TV;>;" },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "mapBuilder_", NULL, 0x12, "Ljava.util.LinkedHashMap;", NULL, "Ljava/util/LinkedHashMap<TK;Ljavax/inject/Provider<TV;>;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _DaggerInternalMapProviderFactory_Builder = { 2, "Builder", "dagger.internal", "MapProviderFactory", 0x19, 3, methods, 1, fields, 0, NULL, 0, NULL, NULL, "<K:Ljava/lang/Object;V:Ljava/lang/Object;>Ljava/lang/Object;" };
  return &_DaggerInternalMapProviderFactory_Builder;
}

@end

void DaggerInternalMapProviderFactory_Builder_initWithInt_(DaggerInternalMapProviderFactory_Builder *self, jint size) {
  NSObject_init(self);
  JreStrongAssign(&self->mapBuilder_, DaggerInternalCollections_newLinkedHashMapWithExpectedSizeWithInt_(size));
}

DaggerInternalMapProviderFactory_Builder *new_DaggerInternalMapProviderFactory_Builder_initWithInt_(jint size) {
  DaggerInternalMapProviderFactory_Builder *self = [DaggerInternalMapProviderFactory_Builder alloc];
  DaggerInternalMapProviderFactory_Builder_initWithInt_(self, size);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMapProviderFactory_Builder)
