//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/MembersInjectors.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "MembersInjector.h"
#include "MembersInjectors.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/NullPointerException.h"

@interface DaggerInternalMembersInjectors ()

- (instancetype)init;

@end

__attribute__((unused)) static void DaggerInternalMembersInjectors_init(DaggerInternalMembersInjectors *self);

__attribute__((unused)) static DaggerInternalMembersInjectors *new_DaggerInternalMembersInjectors_init() NS_RETURNS_RETAINED;

typedef NS_ENUM(NSUInteger, DaggerInternalMembersInjectors_NoOpMembersInjector) {
  DaggerInternalMembersInjectors_NoOpMembersInjector_INSTANCE = 0,
};

@interface DaggerInternalMembersInjectors_NoOpMembersInjectorEnum : JavaLangEnum < NSCopying, DaggerMembersInjector >

- (void)injectMembersWithId:(id)instance;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values();

+ (DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum)

FOUNDATION_EXPORT DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values_[];

#define DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_INSTANCE DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values_[DaggerInternalMembersInjectors_NoOpMembersInjector_INSTANCE]
J2OBJC_ENUM_CONSTANT_GETTER(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum, INSTANCE)

__attribute__((unused)) static void DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *self, NSString *__name, jint __ordinal);

__attribute__((unused)) static DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *new_DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum)

@implementation DaggerInternalMembersInjectors

+ (id<DaggerMembersInjector>)noOp {
  return DaggerInternalMembersInjectors_noOp();
}

+ (id<DaggerMembersInjector>)delegatingToWithDaggerMembersInjector:(id<DaggerMembersInjector>)delegate {
  return DaggerInternalMembersInjectors_delegatingToWithDaggerMembersInjector_(delegate);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  DaggerInternalMembersInjectors_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "noOp", NULL, "Ldagger.MembersInjector;", 0x9, NULL, "<T:Ljava/lang/Object;>()Ldagger/MembersInjector<TT;>;" },
    { "delegatingToWithDaggerMembersInjector:", "delegatingTo", "Ldagger.MembersInjector;", 0x9, NULL, "<T:Ljava/lang/Object;>(Ldagger/MembersInjector<-TT;>;)Ldagger/MembersInjector<TT;>;" },
    { "init", "MembersInjectors", NULL, 0x2, NULL, NULL },
  };
  static const char *inner_classes[] = {"Ldagger.internal.MembersInjectors$NoOpMembersInjector;"};
  static const J2ObjcClassInfo _DaggerInternalMembersInjectors = { 2, "MembersInjectors", "dagger.internal", NULL, 0x11, 3, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_DaggerInternalMembersInjectors;
}

@end

id<DaggerMembersInjector> DaggerInternalMembersInjectors_noOp() {
  DaggerInternalMembersInjectors_initialize();
  return (id<DaggerMembersInjector>) check_protocol_cast(JreLoadStatic(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum, INSTANCE), DaggerMembersInjector_class_());
}

id<DaggerMembersInjector> DaggerInternalMembersInjectors_delegatingToWithDaggerMembersInjector_(id<DaggerMembersInjector> delegate) {
  DaggerInternalMembersInjectors_initialize();
  return (id<DaggerMembersInjector>) check_protocol_cast(delegate, DaggerMembersInjector_class_());
}

void DaggerInternalMembersInjectors_init(DaggerInternalMembersInjectors *self) {
  NSObject_init(self);
}

DaggerInternalMembersInjectors *new_DaggerInternalMembersInjectors_init() {
  DaggerInternalMembersInjectors *self = [DaggerInternalMembersInjectors alloc];
  DaggerInternalMembersInjectors_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMembersInjectors)

J2OBJC_INITIALIZED_DEFN(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum)

DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values_[1];

@implementation DaggerInternalMembersInjectors_NoOpMembersInjectorEnum

- (void)injectMembersWithId:(id)instance {
  if (instance == nil) {
    @throw [new_JavaLangNullPointerException_init() autorelease];
  }
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

IOSObjectArray *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values() {
  DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initialize();
  return [IOSObjectArray arrayWithObjects:DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values_ count:1 type:DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_class_()];
}

+ (IOSObjectArray *)values {
  return DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values();
}

+ (DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *)valueOfWithNSString:(NSString *)name {
  return DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_valueOfWithNSString_(name);
}

DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_valueOfWithNSString_(NSString *name) {
  DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initialize();
  for (int i = 0; i < 1; i++) {
    DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *e = DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [DaggerInternalMembersInjectors_NoOpMembersInjectorEnum class]) {
    DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_INSTANCE = new_DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(@"INSTANCE", 0);
    J2OBJC_SET_INITIALIZED(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "injectMembersWithId:", "injectMembers", "V", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "INSTANCE", "INSTANCE", 0x4019, "Ldagger.internal.MembersInjectors$NoOpMembersInjector;", &DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_INSTANCE, NULL, .constantValue.asLong = 0 },
  };
  static const char *superclass_type_args[] = {"Ldagger.internal.MembersInjectors$NoOpMembersInjector;"};
  static const J2ObjcClassInfo _DaggerInternalMembersInjectors_NoOpMembersInjectorEnum = { 2, "NoOpMembersInjector", "dagger.internal", "MembersInjectors", 0x401a, 1, methods, 1, fields, 1, superclass_type_args, 0, NULL, NULL, "Ljava/lang/Enum<Ldagger/internal/MembersInjectors$NoOpMembersInjector;>;Ldagger/MembersInjector<Ljava/lang/Object;>;" };
  return &_DaggerInternalMembersInjectors_NoOpMembersInjectorEnum;
}

@end

void DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *new_DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(NSString *__name, jint __ordinal) {
  DaggerInternalMembersInjectors_NoOpMembersInjectorEnum *self = [DaggerInternalMembersInjectors_NoOpMembersInjectorEnum alloc];
  DaggerInternalMembersInjectors_NoOpMembersInjectorEnum_initWithNSString_withInt_(self, __name, __ordinal);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(DaggerInternalMembersInjectors_NoOpMembersInjectorEnum)
