//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/MembersInjector.java
//

#ifndef _MembersInjector_H_
#define _MembersInjector_H_

#include "J2ObjC_header.h"

@protocol DaggerMembersInjector < NSObject, JavaObject >

- (void)injectMembersWithId:(id)instance;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerMembersInjector)

J2OBJC_TYPE_LITERAL_HEADER(DaggerMembersInjector)

#endif // _MembersInjector_H_
