//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Module.java
//

#ifndef _Module_H_
#define _Module_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

@protocol DaggerModule < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *includes;

@end

@interface DaggerModule : NSObject < DaggerModule > {
 @private
  IOSObjectArray *includes_;
}

- (instancetype)initWithIncludes:(IOSObjectArray *)includes__;

+ (IOSObjectArray *)includesDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerModule)

J2OBJC_TYPE_LITERAL_HEADER(DaggerModule)

#endif // _Module_H_
