//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/ScopedProvider.java
//

#ifndef _ScopedProvider_H_
#define _ScopedProvider_H_

#include "J2ObjC_header.h"
#include "javax/inject/Provider.h"

@protocol DaggerInternalFactory;

@interface DaggerInternalScopedProvider : NSObject < JavaxInjectProvider >

#pragma mark Public

+ (id<JavaxInjectProvider>)createWithDaggerInternalFactory:(id<DaggerInternalFactory>)factory;

- (id)get;

@end

J2OBJC_STATIC_INIT(DaggerInternalScopedProvider)

FOUNDATION_EXPORT id<JavaxInjectProvider> DaggerInternalScopedProvider_createWithDaggerInternalFactory_(id<DaggerInternalFactory> factory);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalScopedProvider)

#endif // _ScopedProvider_H_
