//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Subcomponent.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "Subcomponent.h"
#include "java/lang/annotation/Documented.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Target.h"

@interface DaggerSubcomponent : NSObject

@end

@interface DaggerSubcomponent_Builder : NSObject

@end

@implementation DaggerSubcomponent

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_TYPE() } count:1 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationDocumented alloc] init] autorelease] } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "modules", "modules", "[Ljava.lang.Class;", 0x401, NULL, NULL },
    { "modulesDefault", "modules", "[Ljava.lang.Class;", 0x100a, NULL, NULL },
  };
  static const char *inner_classes[] = {"Ldagger.Subcomponent$Builder;"};
  static const J2ObjcClassInfo _DaggerSubcomponent = { 2, "Subcomponent", "dagger", NULL, 0x2609, 2, methods, 0, NULL, 0, NULL, 1, inner_classes, NULL, NULL };
  return &_DaggerSubcomponent;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DaggerSubcomponent)

@implementation DaggerSubcomponent_Builder

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_TYPE() } count:1 type:NSObject_class_()]] autorelease], [[[JavaLangAnnotationDocumented alloc] init] autorelease] } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _DaggerSubcomponent_Builder = { 2, "Builder", "dagger", "Subcomponent", 0x2609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DaggerSubcomponent_Builder;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DaggerSubcomponent_Builder)
