//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Subcomponent.java
//

#ifndef _Subcomponent_H_
#define _Subcomponent_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@class IOSObjectArray;

@protocol DaggerSubcomponent < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerSubcomponent)

J2OBJC_TYPE_LITERAL_HEADER(DaggerSubcomponent)

@protocol DaggerSubcomponent_Builder < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerSubcomponent_Builder)

J2OBJC_TYPE_LITERAL_HEADER(DaggerSubcomponent_Builder)

#endif // _Subcomponent_H_
