//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/Beta.java
//

#ifndef _Beta_H_
#define _Beta_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol DaggerInternalBeta < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalBeta)

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalBeta)

#endif // _Beta_H_
