//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/Beta.java
//

#include "Beta.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Documented.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"

@interface DaggerInternalBeta : NSObject

@end

@implementation DaggerInternalBeta

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationDocumented alloc] init] autorelease], [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_SOURCE()] autorelease] } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _DaggerInternalBeta = { 2, "Beta", "dagger.internal", NULL, 0x2609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DaggerInternalBeta;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DaggerInternalBeta)
