//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/Factory.java
//

#include "Factory.h"
#include "J2ObjC_source.h"

@interface DaggerInternalFactory : NSObject

@end

@implementation DaggerInternalFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _DaggerInternalFactory = { 2, "Factory", "dagger.internal", NULL, 0x609, 0, NULL, 0, NULL, 0, NULL, 0, NULL, NULL, "<T:Ljava/lang/Object;>Ljava/lang/Object;Ljavax/inject/Provider<TT;>;" };
  return &_DaggerInternalFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DaggerInternalFactory)
