//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/InstanceFactory.java
//

#ifndef _InstanceFactory_H_
#define _InstanceFactory_H_

#include "Factory.h"
#include "J2ObjC_header.h"

@interface DaggerInternalInstanceFactory : NSObject < DaggerInternalFactory >

#pragma mark Public

+ (id<DaggerInternalFactory>)createWithId:(id)instance;

- (id)get;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalInstanceFactory)

FOUNDATION_EXPORT id<DaggerInternalFactory> DaggerInternalInstanceFactory_createWithId_(id instance);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalInstanceFactory)

#endif // _InstanceFactory_H_
