//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Lazy.java
//

#ifndef _Lazy_H_
#define _Lazy_H_

#include "J2ObjC_header.h"

@protocol DaggerLazy < NSObject, JavaObject >

- (id)get;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerLazy)

J2OBJC_TYPE_LITERAL_HEADER(DaggerLazy)

#endif // _Lazy_H_
