//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/MapKey.java
//

#ifndef _MapKey_H_
#define _MapKey_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol DaggerMapKey < JavaLangAnnotationAnnotation >

@property (readonly) jboolean unwrapValue;

@end

@interface DaggerMapKey : NSObject < DaggerMapKey > {
 @private
  jboolean unwrapValue_;
}

- (instancetype)initWithUnwrapValue:(jboolean)unwrapValue__;

+ (jboolean)unwrapValueDefault;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerMapKey)

J2OBJC_TYPE_LITERAL_HEADER(DaggerMapKey)

#endif // _MapKey_H_
