//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/MembersInjectors.java
//

#ifndef _MembersInjectors_H_
#define _MembersInjectors_H_

#include "J2ObjC_header.h"

@protocol DaggerMembersInjector;

@interface DaggerInternalMembersInjectors : NSObject

#pragma mark Public

+ (id<DaggerMembersInjector>)delegatingToWithDaggerMembersInjector:(id<DaggerMembersInjector>)delegate;

+ (id<DaggerMembersInjector>)noOp;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalMembersInjectors)

FOUNDATION_EXPORT id<DaggerMembersInjector> DaggerInternalMembersInjectors_noOp();

FOUNDATION_EXPORT id<DaggerMembersInjector> DaggerInternalMembersInjectors_delegatingToWithDaggerMembersInjector_(id<DaggerMembersInjector> delegate);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalMembersInjectors)

#endif // _MembersInjectors_H_
