//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/Module.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "Module.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation DaggerModule

@synthesize includes = includes_;

- (instancetype)initWithIncludes:(IOSObjectArray *)includes__ {
  if ((self = [super init])) {
    self->includes_ = RETAIN_(includes__);
  }
  return self;
}

+ (IOSObjectArray *)includesDefault {
  return [IOSObjectArray arrayWithObjects:(id[]){  } count:0 type:IOSClass_class_()];
}

- (IOSClass *)annotationType {
  return DaggerModule_class_();
}

- (NSString *)description {
  return @"@dagger.Module()";
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[[JavaLangAnnotationRetention alloc] initWithValue:JavaLangAnnotationRetentionPolicyEnum_get_RUNTIME()] autorelease], [[[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { JavaLangAnnotationElementTypeEnum_get_TYPE() } count:1 type:NSObject_class_()]] autorelease] } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "includes", "includes", "[Ljava.lang.Class;", 0x401, NULL, NULL },
    { "includesDefault", "includes", "[Ljava.lang.Class;", 0x100a, NULL, NULL },
  };
  static const J2ObjcClassInfo _DaggerModule = { 2, "Module", "dagger", NULL, 0x2609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_DaggerModule;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DaggerModule)
