//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java//dagger/internal/SetFactory.java
//

#ifndef _SetFactory_H_
#define _SetFactory_H_

#include "Factory.h"
#include "J2ObjC_header.h"

@class IOSObjectArray;
@protocol JavaUtilSet;

@interface DaggerInternalSetFactory : NSObject < DaggerInternalFactory >

#pragma mark Public

+ (id<DaggerInternalFactory>)createWithDaggerInternalFactory:(id<DaggerInternalFactory>)factory;

+ (id<DaggerInternalFactory>)createWithJavaxInjectProviderArray:(IOSObjectArray *)providers;

- (id<JavaUtilSet>)get;

@end

J2OBJC_EMPTY_STATIC_INIT(DaggerInternalSetFactory)

FOUNDATION_EXPORT id<DaggerInternalFactory> DaggerInternalSetFactory_createWithDaggerInternalFactory_(id<DaggerInternalFactory> factory);

FOUNDATION_EXPORT id<DaggerInternalFactory> DaggerInternalSetFactory_createWithJavaxInjectProviderArray_(IOSObjectArray *providers);

J2OBJC_TYPE_LITERAL_HEADER(DaggerInternalSetFactory)

#endif // _SetFactory_H_
